### ISSUE TITLE
conveyor belt is very slippery

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#100]
When trying to pickup parts from the conveyor belt, they frequently slip out from under the gripper.  Is it possible to increase the friction on the conveyor belt?

**Comment by zeidk** [comment]
Hi Dan, I am about to release everything for the qualifiers. I am monitoring the posted requests and issues and I will try to address them in the current code, including this one.

**Comment by denbar-robotics** [comment]
It's not that big a deal.  Also, it is probably a bad idea to change a parameter this late in the game, as it might break other competitors code. Consider it something that might be good for next year.  One thing that might help is publishing the gripper status more often, as then the parts might not have a chance to slip.

**Comment by mqt0029** [comment]
Agreed with @denbar-robotics, let's not change anything. Closed #104 as well.
