### ISSUE TITLE
docker issues

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#102]
Trying the new docker stuff. ./run_trial.bash fails with this error:

Error: 'order_0' entry does not contain a required 'products' entry

Looking at the sample trial configs, they are from a previous year and it seems that the docker code is expecting that format.

**Comment by zeidk** [comment]
working on it Dan, I also have this error. The new image is currently being pushed.

**Comment by zeidk** [comment]
Take another look at the documentation on automated evaluation. Pull the new images and rebuild the competitor image.
