### ISSUE TITLE
Github wiki edits generate a ton of commits

### ISSUE THREAD

**Issue by stevegray954** [usnistgov/ARIAC#11]
I'm guessing you are editing the wiki directly on Github.  Please don't.  It makes the commit history difficult to skim through to determine what has changed as we get things like 10 successive commits labeled 'Update automated_evaluation.md'.  It's easier when the commit description is meaningful (and there aren't a ton of them).

Thanks!

**Comment by Pavel-P** [comment]
Sorry about that, the git practices have been all over the place for this project. I'll try to go through and squash the majority of those wiki commits when I get the chance.

**Comment by stevegray954** [comment]
Thanks!

**Comment by zeidk** [comment]
Sorry about this, we will make sure to use better ways to edit the wiki.
Closing this ticket for now.
