### ISSUE TITLE
For frame [ariac/gantry/robot_camera_frame]: Frame [ariac/gantry/robot_camera_frame] does not exist

### ISSUE THREAD

**Issue by barrygxwan** [usnistgov/ARIAC#110]
We can not see point cloud output in RViz,as shown below
![Screenshot from 2021-05-19 17-19-51](https://user-images.githubusercontent.com/27502546/118788530-76bc0100-b8c6-11eb-876b-063f5d58bb04.png)

**Comment by zeidk** [comment]
I will look into this but I think you are missing something somewhere. Please wait till our next push which is aimed to be tomorrow (Friday). Then we can work this issue together.

**Comment by zeidk** [comment]
@Pavel-P I think this is something you should look at. I also experience the same issue and I believe this issue is related to RGBD camera issue to which you are also tagged.

**Comment by zeidk** [comment]
Closing for now. Reopen if needed.
