### ISSUE TITLE
pose not scored for wrong color parts?

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#111]
When I have a part on the tray that is in the correct pose but has a different color than the one specified in the order, the scoring does not give a point for pose.  This is with the merge_april_test branch.

**Comment by zeidk** [comment]
Thanks for letting me know. Was the part of the correct type?

**Comment by dan9thsense** [comment]
yes

**Comment by zeidk** [comment]
Fixed, thank you. I will try to push the new version today.
