### ISSUE TITLE
New software release for finals breaks MoveIt! motion planning on kitting arm

### ISSUE THREAD

**Issue by mqt0029** [usnistgov/ARIAC#113]
MoveIt! motion planning now throws `Invalid Trajectory: start point deviates from current robot state more than 0.01` for kitting arm. Gantry seems to be working correctly.

**Comment by glpuga** [comment]
Same for me.

The problem seems to be related to this change: https://github.com/usnistgov/ARIAC/blame/master/nist_gear/launch/kitting.launch#L29

Changing  `wrist_1_joint` to something in a smaller range (`-J wrist_1_joint 1.00`) fixed the problem for me.

**Comment by mqt0029** [comment]
thanks for the suggestion @glpuga. This seems to be a sufficient temporary fix on my end.

**Comment by glpuga** [comment]
yw!

Maybe it's better to leave this issue open so that it can be checked to see if it needs addressing on the competition code.

**Comment by mqt0029** [comment]
Reopened in case this become an issue in final rounds.

**Comment by zeidk** [comment]
Thank you. Yes, the moveit package was not modified (last modification was made 28 days ago). I will modify the launch file on my side and push it again.

**Comment by glpuga** [comment]
This looks fixed for me now. Thanks!

**Comment by zeidk** [comment]
Thanks!
