### ISSUE TITLE
Regulator parts are invisible in after May 28th update

### ISSUE THREAD

**Issue by glpuga** [usnistgov/ARIAC#115]
After the update, whenever `assembly_regulator_red` parts are present in the trial configuration the simulation takes a long time to load (gazebo pauses for a long time in "Preparing your world...").

Once the simulation loads, `assembly_regulator_red` parts are not visible in gazebo but they are perceived by the logical cameras.

**Comment by mqt0029** [comment]
Similar problem, invisible part. I did not have the long "Preparing your world" issue though.

**Comment by zeidk** [comment]
Ok, this should be a quick fix, I will handle this today.

**Comment by zeidk** [comment]
Should be fixed now.

**Comment by glpuga** [comment]
This is fixed for me now. Thanks!
