### ISSUE TITLE
robot cannot pick the faulty part after the blocked sensor return normal !!!!!

### ISSUE THREAD

**Issue by YunpengHe** [usnistgov/ARIAC#116]
We found a bug that:
      our robot can pick part normally, before and after sensor blocked. 
      when we pick the faulty part  (placed during sensor is blocked ) on agv, we make sure that the gripper of kitting robot is enabled. **And gripper is attached the faulty part obviously, but the gripper cannot pick up the part.** For other part, robot can pick normally !   Only kitting robot has this problem, gantry_robot can pick the faulty part after after the blocked sensor return normal. For now, we have tested pump and sensor, these two part have the same issue as above
![Screenshot from 2021-05-30 09-39-00](https://user-images.githubusercontent.com/71024833/120089227-e6ce5080-c12a-11eb-8e04-7bc4705c0598.png)

**Comment by YunpengHe** [comment]
For now, we have tested pump and sensor, these two part have the same issue as above

**Comment by zeidk** [comment]
Do you get similar outputs as the ones described in #109 ?

**Comment by YunpengHe** [comment]
yes, I have similar outputs

**Comment by zeidk** [comment]
I'm working on this issue and it should be fixed today. However, the issue happens when the faulty gripper challenge is in use while your issue seems to be related to faulty sensors. Once the new push is made, give it a try and see if your issue is gone.

**Comment by YunpengHe** [comment]
Yes, It works!

**Comment by zeidk** [comment]
Great!!
