### ISSUE TITLE
Question about updates to the properties of the assembly_sensor_blue model

### ISSUE THREAD

**Issue by glpuga** [usnistgov/ARIAC#117]
This is not so much an issue but more of a question:

Is [the change of mass from 0.5 to 1.0](https://github.com/usnistgov/ARIAC/commit/a97e234365acf07651cf385490c20a7f65c52b9e?branch=a97e234365acf07651cf385490c20a7f65c52b9e&diff=split#diff-7d1decf23332a60e605a7c0a84e5fa08822895fdb6aa8b6c12251da33cff1f7bR8) to the `assembly_sensor_blue` model an intended change?

I wonder because all other model's mass remained the same after updates (0.5). 

Also, only `blue sensors` were updated; the red and green sensors properties were not updated:

I wouldn't have realized if not because after updating picking up blue sensors started failing for me because of tolerance issues.

**Comment by zeidk** [comment]
I was messing around with different masses trying to fix a former issue. It seems I forgot to change it back to 0.5. You can change it back to 0.5 on your system and I will push the new change sometime today. Thanks!

**Comment by glpuga** [comment]
Thanks!
