### ISSUE TITLE
There are is no sensor or regulator assembly task!!! 

### ISSUE THREAD

**Issue by YunpengHe** [usnistgov/ARIAC#118]
In the current final practices, there are no sensor or regulator assembly task, is it will evaluated in the final competition?

**Comment by zeidk** [comment]
@Pavel-P This is related to the assembly plugin. We should give an answer today so that competitors are set on this matter.

**Comment by denbar-robotics** [comment]
There was an earlier note that said there would only be two types of products for assembly tasks in the finals.  Please do not make a late change to that.

**Comment by zeidk** [comment]
After discussion, the only parts used for assembly this year are batteries and pumps. I'm closing this ticket and I will convey this message in the next github push.

**Comment by YunpengHe** [comment]
we have made a solution for assembly sensor or regulator......

**Comment by zeidk** [comment]
I really appreciate the help. We won't include assembly with these 2 other parts as it requires more time for competitors to test new strategies. However, you can send me an email with your solution if you want. We would like to reuse the same scenarios and theme for ARIAC next year.
