### ISSUE TITLE
poses shift when trays move?

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#120]
I submitted a kitting order where I am pretty sure the poses were all correct before the tray moved, but looks like the parts shifted when the tray moved and the pose scoring said only 2 of the 3 parts were in the correct pose.  Is the pose scoring done before the tray moves or after?

**Comment by zeidk** [comment]
Everything is scored before the agv moves. You can try one of the bash scripts in the script folder to check this. Eventually you can create a kitting order with 2 or 3 parts, spawn the parts on the AGV, and ship the AGV.

**Comment by denbar-robotics** [comment]
OK, I'll check it again.

**Comment by zeidk** [comment]
Did you check this one?

**Comment by denbar-robotics** [comment]
I haven't had a chance to check it yet-- busy fixing the code to deal with the moving AGVs.

**Comment by zeidk** [comment]
I assume this worked for you.

**Comment by denbar-robotics** [comment]
I've been too busy to test it.  Fine to close it.  If I have time to check it later I'll let you know.
