### ISSUE TITLE
log playback fails

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#123]
Trying to view the state.log files from the finals results.  The playback script fails:

Here is the command used:
roslaunch nist_gear gear_playback.launch state_log_path:=/home/dbarry/Dropbox/ariac/ariac_2021/finals_results_2021/sirius_trial_logs/sirius_A2/gazebo/state.log

Here is the error (many of these appeared).  Looks like the problem is due to absolute file paths.

[ INFO] [1625181620.621522544]: Finished loading Gazebo ROS API Plugin.
[Wrn] [msgs.cc:1852] Conversion of sensor type[depth] not supported.
[Wrn] [SystemPaths.cc:464] File or path does not exist ["/home/zeid/ariac2021/src/ARIAC/nist_gear/robots/gantry/gantry_description/meshes/torso_base.dae"] [/home/zeid/ariac2021/src/ARIAC/nist_gear/robots/gantry/gantry_description/meshes/torso_base.dae]
[Err] [MeshShape.cc:60] No mesh specified

**Comment by zeidk** [comment]
Closing for now. Reopen if needed.
