### ISSUE TITLE
2022 wiki folder has not been updated

### ISSUE THREAD

**Issue by 130s** [usnistgov/ARIAC#125]
We received the software release announcement. I assume the technical documentation is collected at https://github.com/usnistgov/ARIAC/tree/ariac2022/wiki
If that's correct, the entire folder has not been updated since 10 months ago (viewed on 2022/03/25). I see lots of "2021" mentioned too.

Is there a plan for an up update? Am I looking at a wrong location?

**Comment by zeidk** [comment]
It should be up now.
Give it a try.
