### ISSUE TITLE
logical camera coverage

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#126]
The image shown on the [sensor interface page](https://github.com/usnistgov/ARIAC/blob/ariac2022/wiki/tutorials/sensor_interface.md) shows a logical camera with a much larger area of coverage than in previous years.  However, upon running the sim with sample_environment.launch, the coverage looks about the same as before.  Which one is correct?

![world_gzclient_camera(1)-2022-03-28T00_26_57 194093](https://user-images.githubusercontent.com/78889039/160326744-2975dddd-9036-4997-846c-3dae9f712b6e.jpg)

**Comment by zeidk** [comment]
The image on the wiki is wrong. The one you see in simulation is the correct fov. Will fix.
