### ISSUE TITLE
motion planning fails for the full group

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#127]
Moveit robot planning in the assembly robot works for the gantry_torso and for the gantry_arm groups but it fails for the combined gantry_full group.  

It's a pretty simple fix to gantry_moveit_config/config/kinematics.yaml  Just make the solver for gantry_full the same as the solver for the other two groups.  Doing that makes gantry_full planning work fine.
I found that someone else previously ran into the same bug and has the [same solution](https://githubhot.com/repo/usnistgov/ARIAC/issues/108).

- kinematics_solver: cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin
+ kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin

**Comment by zeidk** [comment]
I will take a look and see how it behaves. What happens when it fails? What do the errors look like?

**Comment by denbar-robotics** [comment]
(plan, fraction) = group.compute_cartesian_path(
    waypoints,  # waypoints to follow
    0.01,  # eef_step
    0.0,  # jump_threshold = max radians allowed in a joint for a single step
    False)  # do not avoid collisions


[ERROR] [1645207759.372480196, 533.557000000]: Seed state must have size 9 instead of size 13
[ERROR] [1645207759.373198667, 533.557000000]: Service call failed to connect to service: /ariac/gantry/solve_ik

**Comment by zeidk** [comment]
It should be pushed now.

**Comment by denbar-robotics** [comment]
It works fine, thanks.
