### ISSUE TITLE
Questions regarding movable trays

### ISSUE THREAD

**Issue by glpuga** [usnistgov/ARIAC#133]
Are these scenarios possible?

- The movable tray needs to be replaced for one of a different type, either because the scene started with an unwanted movable tray in the agv (I think this is not possible to configure in the yaml file) or because of an update the a previous order (this case is probably possible). This would require removing all the parts, replacing the tray, then loading the new parts on.
- An agv used for a kitting order starts the simulation with parts loaded on them but no movable tray, requiring all parts to be removed  to place the movable tray before completing the rest of the order.

**Comment by zeidk** [comment]
Hello, none of these scenarios will be encountered in a trial. Thanks for the questions, I will update the wiki with them.

**Comment by glpuga** [comment]
Thanks for the answer!

**Comment by zeidk** [comment]
Wiki updated to answer your questions
