### ISSUE TITLE
trays move around on agvs

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#134]
The movable tray slips and slides around very easily on the agv.  Once it moves, it can be very hard to reset into place, as there may be parts sitting on it.  Is there any way to increase the friction or perhaps lock the tray in place on the agv?

**Comment by zeidk** [comment]
Yes, we can lock it in place through a service call. The code for this service is already in an ARIAC .cc file, I just need to uncomment it.

**Comment by denbar-robotics** [comment]
Thanks.  And appreciate the response late on a Sunday night!

**Comment by zeidk** [comment]
I will make another push tomorrow, which will also address the other questions from other users.

:)

**Comment by zeidk** [comment]
Did you get a chance to try the service which locks/unlocks movable trays? Can I close this ticket?

**Comment by denbar-robotics** [comment]
I didn't see that service show up.  I'll look for it and try tonight.

**Comment by zeidk** [comment]
Ok, see the [updates](https://github.com/usnistgov/ARIAC/blob/ariac2022/wiki/misc/updates.md#release-2022-april-9) for more information.

**Comment by denbar-robotics** [comment]
The tray stays in place now but the parts go flying off it when submitted.

**Comment by zeidk** [comment]
Well I tried this situation a few times and it worked fine. I'll check what's wrong.

**Comment by denbar-robotics** [comment]
The scorer recognizes that the part was there, so the parts fly off after scoring.  A pump ends up back behind the conveyor!

**Comment by denbar-robotics** [comment]
The service returned result is False, but the message says it worked.  And it does work.  Also, you get messages that say the tray is locked/unlocked from agvs that have no movable trays on them

rosservice call /ariac/kit_tray_2/lock
success: False
message: "Movable tray is now locked on the kit tray"

**Comment by denbar-robotics** [comment]
It works well enough to close the issue.  The wrong boolean return message is no big deal.
