### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#135]
About once every five or so launches, gear fails with this message:

[ INFO] [1649198019.310798403]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ WARN] [1649198019.315425540]: spawnURDFModel service called
[ WARN] [1649198019.316320590]: spawnSDFModel service called
[INFO] [1649198019.349839, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1649198019.423852, 0.000000]: Calling service /gazebo/spawn_urdf_model
gzserver: /usr/include/boost/smart_ptr/enable_shared_from_this.hpp:51: boost::shared_ptr<X> boost::enable_shared_from_this<T>::shared_from_this() [with T = gazebo::transport::Node]: Assertion `p.get() == this' failed.
Service call failed: transport error completing service call: unable to receive data from sender, check sender's logs for details
Service call failed: transport error completing service call: unable to receive data from sender, check sender's logs for details
Service call failed: transport error completing service call: unable to receive data from sender, check sender's logs for details
[ERROR] [1649198021.671248, 0.000000]: Spawn service failed. Exiting.
[ERROR] [1649198021.671190, 0.000000]: Spawn service failed. Exiting.
[ERROR] [1649198021.671297, 0.000000]: Spawn service failed. Exiting.
Aborted

When it works, that section looks like this:

[ INFO] [1649198220.582981116]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ WARN] [1649198220.680340876]: spawnURDFModel service called
[ WARN] [1649198220.680558775]: spawnSDFModel service called
[INFO] [1649198220.763483, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1649198220.824396, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1649198223.150374, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[ WARN] [1649198223.150987895]: spawnURDFModel service called
[ WARN] [1649198223.152040661]: spawnSDFModel service called
[ INFO] [1649198223.161381877]: Physics dynamic reconfigure ready.
[spawn_gazebo_sensors-18] process has finished cleanly
log file: /home/dbarry/.ros/log/e51f5da6-b530-11ec-a205-181deaec5b6c/spawn_gazebo_sensors-18*.log
[ WARN] [1649198223.449795180]: spawnURDFModel service called
[INFO] [1649198223.449990, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[ WARN] [1649198223.450452214]: spawnSDFModel service called
[INFO] [1649198223.451221, 0.000000]: Waiting for service /gazebo/set_model_configuration
[INFO] [1649198223.452937, 0.000000]: temporary hack to **fix** the -J joint position option (issue #93), sleeping for 1 second to avoid race condition.
[ INFO] [1649198223.712811894]: Loading gazebo_ros_control plugin
[ INFO] [1649198223.712951987]: Starting gazebo_ros_control plugin in namespace: /ariac/gantry
[ INFO] [1649198223.713369556]: gazebo_ros_control plugin is waiting for model URDF in parameter [/ariac/gantry/robot_description] on the ROS param server.
[ INFO] [1649198223.838093158]: Loaded gazebo_ros_control.

**Comment by zeidk** [comment]
I will look into this today. It has to do with one of the Gazebo plugins.

**Comment by zeidk** [comment]
Could you send me your performance.log file whenever this issue arises again. I cannot reproduce it on my end but it seems a plugin is not loading due to a slow machine.

**Comment by denbar-robotics** [comment]
sent

**Comment by zeidk** [comment]
I haven't see this issue for a while. Reopen if you still see it.

**Comment by db7296** [comment]
Yes, it still happens.  There is no option available to re-open.  Should I create a new issue?
