### ISSUE TITLE
sensor falls out of briefcase

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#137]
I am wondering if anyone else has this issue:  When the sensor is placed in the briefcase and released, it just falls out onto the floor.

**Comment by zeidk** [comment]
@jaybrecht @Pavel-P Could you please assist with this ticket? It seems an advice is required here instead of an actual technical fix.

**Comment by jaybrecht** [comment]
@denbar-robotics The plugin that registers that the assembly was completed and locks the part in place requires the sensor to be inserted completely. Have you tried increasing the depth of install? If you are still having issues would you be able to attach a video of the problem so that we can see?

**Comment by jaybrecht** [comment]
Here is a video of the test competitor installing the sensor to briefcase_1. 

![output](https://user-images.githubusercontent.com/50928580/162782629-63301d3c-ae68-404e-b3af-32247a240199.gif)


You can test this yourself. In the first terminal run
`roslaunch test_competitor assembly.launch station:=as1`
In the second run:
`rosrun test_competitor assembly_commander_node.py`

**Comment by denbar-robotics** [comment]
oh, didn't know that. I'll give it a try.  Is that true for the regulator too?

**Comment by jaybrecht** [comment]
Yes the regulator works in a similar way. I will close this issue for now but let us know if you have any other issues.
