### ISSUE TITLE
Automated Evaluation details are missing

### ISSUE THREAD

**Issue by AravindaDP** [usnistgov/ARIAC#142]
Now that Qualifier smoke test is next week, Details of automated evaluation is still not updated

https://github.com/usnistgov/ARIAC/blob/ariac2022/wiki/documentation/automated_evaluation.md

Also IMHO this year competition time line seems bit tough for the new coming teams given that release of competition software and documentation was bit delayed than usual.

**Comment by zeidk** [comment]
This will be taken care of in tomorrow's push
