### ISSUE TITLE
Agv2,3,4 shipment product drops

### ISSUE THREAD

**Issue by liuhaoran1** [usnistgov/ARIAC#145]
When I submit the kitting task on AGV2,3 and 4, the products and movable trays will fall to the ground during transportation, but this will not happen in AGV1. The final score display does not affect the score situation. 
 I don't know if other competitors in the same situation

**Comment by zeidk** [comment]
I will test this on my end and will update accordingly.

**Comment by liuhaoran1** [comment]
> 我将对此进行测试，并进行相应的更新。

thinks，so this problem is the common issue for all competitors，right？

**Comment by zeidk** [comment]
This should have been fixed. Please give it a try and close this ticket if the issue has gone away.
