### ISSUE TITLE
machine dependent issues

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#147]
There are a number of things that I find are machine dependent.  For example, arm placements are slightly more accurate on a faster machine.  This leads to a dilemma when deciding some behaviors-- which machine to go with?  Can you specify the instance type of the machine that will be used for evaluation?  That would make it easier to decide which machine to do final tweaks with.

**Comment by zeidk** [comment]
I will be using this configuration:
![ubuntu_specs](https://user-images.githubusercontent.com/8428984/167059774-c9a18ee8-93b3-4db0-8f1e-47b45650af18.png)

**Comment by denbar-robotics** [comment]
fixed by testing on a cloud server.
