### ISSUE TITLE
submit service fails

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#148]
The submit service often fails with this message and it crashes the sim:

terminate called after throwing an instance of 'std::out_of_range'
[ERROR] [1650398217.055792155, 264.546000000]: Exception thrown while processing service call: basic_string::substr: __pos (which is 19) > this->size() (which is 18)
  what():  basic_string::substr: __pos (which is 19) > this->size() (which is 18)

**Comment by liuhaoran1** [comment]
This was also the case when I submitted the Assembly

**Comment by mqt0029** [comment]
Now seeing the same issue.

**Comment by AravindaDP** [comment]
I also get the same error with `roslaunch test_competitor assembly.launch station:=as1` and assembly_commander example

It does not fail with `roslaunch test_competitor assembly.launch station:=as1_simple` but Score is 0.

**Comment by db7296** [comment]
this is now fixed.

**Comment by dan9thsense** [comment]
fixed.
