### ISSUE TITLE
Gantry only spawns if 'development_mode' is set to true

### ISSUE THREAD

**Issue by stevegray954** [usnistgov/ARIAC#15]
I noticed in the sample launch file that development mode is set to true.  Removing the `--development-mode` flag causes the gantry not to spawn.

I had thought all the `development-mode` flag did was enable the cheat topics on the [interface page](https://github.com/usnistgov/ARIAC/blob/b9afa1389f5232c48b85469b0a1397436471d0b7/wiki/competition_interface_documentation.md), but it seems to be doing something else.

```
  <node name="ariac_sim" pkg="nist_gear" type="gear.py"
        args="--development-mode
          $(arg verbose_args)
          $(arg state_logging_args)
          $(arg gui_args)
          $(arg load_moveit_args)
          $(arg fill_demo_shipment_args)
          --visualize-sensor-views
          -f $(find nist_gear)/config/sample.yaml
          $(find nist_gear)/config/sample_user_config.yaml
          " required="true" output="screen" />
```

From `gear.py`
```
if not args.development_mode:
    os.environ['ARIAC_COMPETITION'] = '1'
```
I'm pretty sure we weren't allowed to run in development mode for the actual scored competition runs.

**Comment by Pavel-P** [comment]
Make sure you're using the custom version of gazebo_ros_pkgs mentioned in the [wiki](https://github.com/usnistgov/ARIAC/blob/master/wiki/tutorials/installation.md), the debian package blocks the spawn_urdf_model service from completing when ros networking is disabled in competition mode.

**Comment by stevegray954** [comment]
Thanks, adding the nonstandard `gazebo-ros` version fixed it.

For anyone looking at it later, the solution was to clone this into your catkin workspace:
```
git clone https://github.com/osrf/ariac-gazebo_ros_pkgs -b ariac-network-melodic
```
