### ISSUE TITLE
part is stuck to tray

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#150]
when using the gantry arm to pick up a part that was delivered by the kitting arm and submitted on a movable tray, the part sticks to the (locked) tray and they come off the agv attached to each other.  Nevertheless the code valiantly delivered them both to the briefcase :)
![pump_stuck_to_tray](https://user-images.githubusercontent.com/78889039/164164835-b9c3b0fd-50d8-4003-b13c-69381ff495cd.png)
.

**Comment by db7296** [comment]
Since the trays are never unlocked, this is fixed.

**Comment by denbar-robotics** [comment]
fixed
