### ISSUE TITLE
movable tray orientation

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#152]
Orders received specify a movable tray orientation, but the dev.yaml (and no other that I could find) trial config does not show how to specify it.  It just has:

      trays: [movable_tray_metal_shiny]

If it is not always in the default orientation (x,y,z,r,p,y = 0,0,0,0,0,0 in the kit_tray frame), how is it specified in the trial config file?

**Comment by zeidk** [comment]
The pose of movable trays is hardcoded and it will always be consistent between trials.
