### ISSUE TITLE
locked movable tray falls off agv with new update

### ISSUE THREAD

**Issue by db7296** [usnistgov/ARIAC#156]
With the new code, moving an agv causes the tray to fall off the agv.  The call to lock the tray returned with the same message as before the code update-- it is an ambiguous result, as it says the call failed because the tray was already locked.  However, no previous call was made to lock the tray.  However, in the previous version, the tray stayed in place after the call; now it drops off the agv.

[INFO] [1651252304.942284, 37.714000]: waiting for lock_movable_tray service /ariac/kit_tray_1/lock
[INFO] [1651252304.944533, 37.715000]: calling lock_movable_tray service /ariac/kit_tray_1/lock
lock result:  success: False
message: "Movable tray is already locked on the kit tray"

https://user-images.githubusercontent.com/83300520/165991674-075c0b51-4f95-4236-8475-ad1cc722e0b1.mp4

**Comment by zeidk** [comment]
Does the tray fall off after you use the submit service call or the move_to service call? Or both?

**Comment by db7296** [comment]
move_to_station service call

**Comment by db7296** [comment]
This is no longer a move I try to make.
