### ISSUE TITLE
Submission procedure has not been updated！！！？

### ISSUE THREAD

**Issue by wanguangxi** [usnistgov/ARIAC#157]
Hello， the quilifier test is comming soon. But the  submission procedure has not been updated of ariac 2022. So, when will it be updated?

**Comment by AravindaDP** [comment]
Also with latest update time for Qualification round has reduced from 5/6 as announced last week to 5/2 Appreciate if it can be allowed until 5/6 as extended last week.

**Comment by zeidk** [comment]
I'm working on this. The OSRF keys do not work anymore.
