### ISSUE TITLE
When disable development mode, gripper change is impossible

### ISSUE THREAD

**Issue by mqt0029** [usnistgov/ARIAC#158]
When launching using `roslaunch`, without the `--development-mode` flag, gripper change will always returns a `success: False`. The attached image is shown the gantry at the exact same location, one with development mode off, and the later on. Can't determine on test_competitor code since it depends on the `--development-mode` flag.

![Screenshot from 2022-04-30 00-18-14](https://user-images.githubusercontent.com/46615495/166092348-a793742f-0601-44a0-88e3-55aeb07e68bd.png)

**Comment by zeidk** [comment]
Thanks, I will take a look now.

**Comment by zeidk** [comment]
Should be fixed in latest update.

**Comment by mqt0029** [comment]
Confirmed. Working without `--development-mode` flag. Thank you!
