### ISSUE TITLE
Clarifications on Qualifier Round Scope

### ISSUE THREAD

**Issue by AravindaDP** [usnistgov/ARIAC#159]
According to update on 4/28 following are the challenges on qualifier round
- Flipped part 
- Faulty parts
- Sensor blackout

Apart from that we assume Gripper change will anyway be required

1. Can you confirm that handling following challenges will not be required to pass the qualification round?
- Faulty Gripper (Dropped parts)
- Insufficient Products
- High-priority Orders
- Robot Breakdown
- Human Obstacles 

2. Also will there be necessity to pick parts from conveyor belt? Or always there will be sufficient products on bins to fulfill the orders?

**Comment by zeidk** [comment]
Good questions. We usually do not tell competitors what to expect during qualifiers but with the increasing complexity of ARIAC we wanted competitors to focus on certain aspects to get their feet wet before the finals.

I confirm that the challenges listed in 1. will not be part of the trials used in the qualifiers.
Yes, picking up parts from the belt will be required. Picking up parts from bins and from AGVs (for assembly) will also be required.
