### ISSUE TITLE
state playback fails

### ISSUE THREAD

**Issue by db7296** [usnistgov/ARIAC#164]
Trying to review docker results.  The instructions say:

The easiest way to not get these errors is to create the following directory structure on the host /home/ariac/ariac_ws/src/nist_gear, then copy the whole robots directory from ARIAC into it. The path will finally be /home/ariac/ariac_ws/src/nist_gear/robots. Note: Make sure you are working in the /home directory and not in the Home directory ~.

and I did all that, just as in previous years, but state.log playback generates this error:

[ INFO] [1651869487.974693261]: Finished loading Gazebo ROS API Plugin.
[Wrn] [FuelModelDatabase.cc:248] URI not supported by Fuel [Map #61.jpg]
[Wrn] [SystemPaths.cc:464] File or path does not exist [""] [Map #61.jpg]
[Err] [Material.cc:96] Unable to find texture[Map #61.jpg] in path[~/ariac_ws/src/ARIAC/nist_gear/models/kit_tray_table_ariac/meshes]

And, sure enough, opening the file "~/ariac_ws/src/ARIAC/nist_gear/models/kit_tray_table_ariac/meshes/tray_table.dae"
in meshlab generates the same error.

**Comment by zeidk** [comment]
These warning and errors also show up in the normal competition, see performance.log. I don't think this is the origin of the issue but I should be able to test it today.

**Comment by db7296** [comment]
works now.
