### ISSUE TITLE
Automated Evaluation Issues

### ISSUE THREAD

**Issue by AravindaDP** [usnistgov/ARIAC#166]
Here I'm listing down issues encountered while using automated evaluation procedure. Feel free to add additional Issue reporting if you have.

1. Partial score for visually perfect assembly task. 
trial_config: 
[assembly_as1.yaml.txt](https://github.com/usnistgov/ARIAC/files/8644598/assembly_as1.yaml.txt) (Note that txt extension added for uploading)
 logs:
[assembly_as1.zip](https://github.com/usnistgov/ARIAC/files/8644596/assembly_as1.zip)

2. Gazebo crash on kitting_assembly_sample.
trial_config: 
[kitting_assembly_sample.yaml.txt](https://github.com/usnistgov/ARIAC/files/8644632/kitting_assembly_sample.yaml.txt)
logs:
[kitting_assembly_sample.zip](https://github.com/usnistgov/ARIAC/files/8644634/kitting_assembly_sample.zip)
Note that it is not entirely clear if it's due to competitor code error since there is a warning regarding `Controller is taking too long to execute trajectory` But in any case it's not expected to have the competition server to crash due to (bug?) in competitors code.
Note that when kitting task is removed from same order assembly task succeeds. (Even though it gives 0 sore potentially due to Issue 1 above)
[kitting_assembly_only.zip](https://github.com/usnistgov/ARIAC/files/8644641/kitting_assembly_only.zip)

**Comment by zeidk** [comment]
OK, I will try this myself today. Note that if a type of trial does not work in docker then it will not be used during the qualifier. Thanks for the log files.

**Comment by zeidk** [comment]
This should be good now. Let me know if you have other issues after I upload the new image.

**Comment by AravindaDP** [comment]
Assembly scoring is working correctly now. But Gazebo crash still persists.

Also please publish the updated docker images
