### ISSUE TITLE
segmentation faults

### ISSUE THREAD

**Issue by liuhaoran1** [usnistgov/ARIAC#169]
I am encountering segmentation faults in various situations.Causing Gazebo to quit.
I can't test how much score I can get.
I don't know how to solve it

**Comment by zeidk** [comment]
does it happen when you submit an agv or assembly?

**Comment by liuhaoran1** [comment]
yes，this error occurs when orders are more complex.
When will the qualifying results be announced？

**Comment by zeidk** [comment]
Closing for now.
