### ISSUE TITLE
Please update the important dates. Due to the delay in qualifying, the existing dates are a bit confusing

### ISSUE THREAD

**Issue by wanguangxi** [usnistgov/ARIAC#171]

**Comment by AravindaDP** [comment]
Also Just pointing that Deadline mentioned on challenge.gov is June 3rd ;-) https://www.challenge.gov/?challenge=ariac-2022&tab=overview

**Comment by zeidk** [comment]
Yes, June 3rd :)
I will update it. For now, the only date you need to focus on is June 3rd.

Thank you,

zeid
