### ISSUE TITLE
conveyor parts

### ISSUE THREAD

**Issue by db7296** [usnistgov/ARIAC#174]
The update notes say conveyor parts "are spawned in the middle of the belt."  Is this a change?  They have previously spawned at the right hand end.  Also, seems like then half the belt will not get used.  Or does this just mean the middle of the belt in the world x direction?

**Comment by db7296** [comment]
also, seems kind of late to announce that the gantry robot needs to be able to pick up conveyor parts.

**Comment by zeidk** [comment]
Bad wording, nothing has changed on the way parts spawn on the belt. I was providing more information on the location of the parts on the belt, they are in the center of the moving belt. Robot breakdown can happen any time during kitting, it is implied that the kitting robot can break down. Nothing new is announced but rather making sure competitors thought of this situation.

**Comment by db7296** [comment]
ok
