### ISSUE TITLE
Warning when loading robot model

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#18]
Not a big deal, but something to clean up.  When the robot model is loaded, a warning is generated:

[ WARN] [1583863722.975019695]: Skipping virtual joint 'virtual_joint' because its child frame 'long_rail_1' does not match the URDF frame 'world'

**Comment by Pavel-P** [comment]
Fixed in adfcb843b1426c1407014404d5eb81b41e9fa54c.
