### ISSUE TITLE
replacing movable trays needed?

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#180]
Is it a possible trial configuration to have the wrong type of movable tray already present on an agv at startup, so that it has to be removed before the correct movable tray type is placed?  If so, would it be locked?

**Comment by zeidk** [comment]
This situation will not happen. The only time parts are located on an AGV when simulation starts is when assembly is required and the AGV will start with parts at the assembly station. Even in that case parts are directly placed on the kit tray and there is no movable tray involved.

**Comment by dan9thsense** [comment]
Thanks for the fast response.
