### ISSUE TITLE
Problem with moveit_servo dependency

### ISSUE THREAD

**Issue by JADC362** [usnistgov/ARIAC#185]
# Problem
When installing the dependency packages of ARIAC repo, I couldn't successfully run `rosdep install` command, since `moveit_servo` is not found, even after installing all the binaries of `moveit` (`sudo apt install ros-galactic-moveit`).

**Comment by JADC362** [comment]
How did you install this package? Did you do it by binary installation? Or did you clone the entire repo and build it from source?

**Comment by Pavel-P** [comment]
All dependencies should properly install through rosdep. Make sure you're running `sudo rosdep init` and `rosdep update --include-eol-distros` before the install step.

**Comment by maxymczech** [comment]
@Pavel-P Shouldn't this information be included in the installation guide?

**Comment by Pavel-P** [comment]
Yep, we'll add it next time we push an update to the documentation
