### ISSUE TITLE
updated order not sent until original order submitted

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#19]
Working on sample2.yaml, the updated order does not arrive until immediately after the original order is submitted.  The original order had 5 parts and the update conditions are:

announcement_condition: wanted_products
    announcement_condition_value: 4

Changing  announcement_condition_value to 2 makes no difference, the order update still does not happen until after submission of the filled first order.

Changing the condition to time works OK.

**Comment by dan9thsense** [comment]
The problem is that the original order does not fill enough wanted parts to trigger the updated order.  Modifying the wanted products fixes the problem

**Comment by zeidk** [comment]
Thank you Dan.
