### ISSUE TITLE
Human challenge causing gazebo to crash

### ISSUE THREAD

**Issue by akashjinandra** [usnistgov/ARIAC#207]
Hello,

when running the human challenge with the test competitor package it seems to immediately crash gazebo. 
![image](https://user-images.githubusercontent.com/22859817/224577017-c53ad59a-f657-4e02-a549-0084fa481068.png)

**Comment by zeidk** [comment]
Hello, there is a note in the documentation mentioning that the human challenge will be added at a later date.
https://ariac.readthedocs.io/en/latest/getting_started/updates.html

The human challenge cannot be used in the current version of the software.
