### ISSUE TITLE
scoring system and Gazebo  crash

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#217]
"In testing, I found that there were some issues with the scoring system. For example, when I called the '/ariac/move_agv{}' service to move the AGV to a specified location, the scoring system sometimes showed that the AGV did not reach the target position. This situation occurs quite frequently. The same problem also occurs during assembly tasks, where it shows 'Incorrect Poses'. Additionally, another issue is that parts falling off can cause Gazebo to crash."

**Comment by jaybrecht** [comment]
I have created a separate issue for tracking the gazebo crash #218. 

For understanding the issue with the kitting scoring system can you provide:
- the snippet of the trial configuration yaml file from the order
- a screenshot of the environment when you submitted the order 
- the output from the environment terminal when the order was submitted

Also a similar thing would be helpful for diagnosing the issue with scoring assembly tasks.

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/228204771-e82f3141-88fc-4bdb-9afe-084bbaf1991d.png)
this is kitting.yaml

`# Trial Name: qc.yaml

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [3, 8] 
  slots: [1, 4]

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin2:
      - type: 'pump'
        color: 'purple'
        slots: [1, 3, 7, 9]
    bin1:
      - type: 'battery'
        color: 'purple'
        slots: [1, 3, 7, 9]
    bin3:
      - type: 'sensor'
        color: 'purple'
        slots: [1, 3, 7, 9]
    bin4:
      - type: 'regulator'
        color: 'purple'
        slots: [1, 3, 7, 9]
    
orders:
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'pump'
          color: 'purple'
          quadrant: 1
        - type: 'battery'
          color: 'purple'
          quadrant: 4
        `

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/228207425-60a75e8e-3072-452d-a456-415f5835b4d2.png)
![image](https://user-images.githubusercontent.com/114295414/228208161-a5757d9d-1632-4ad6-a602-19b279b36c7c.png)
this is another trial result

**Comment by jaybrecht** [comment]
For both trials do you wait until the AGV has reached the destination before submitting the order?

**Comment by LKmubihei** [comment]
Currently, I am moving the AGV by invoking function services, without strictly checking whether the AGV has reached the specified position. It is worth mentioning that I used sample code for testing, and when I placed the parts in the 1st and 4th quadrants, it showed "destination: no", while it worked normally when I placed the parts in the 2nd and 3rd quadrants.

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/228220970-968eb431-d0cf-437c-87c8-7d461c1d8a36.png)

**Comment by jaybrecht** [comment]
You should not need to check the AGV location necessarily. As long as you wait for the response from the move_AGV service that should be sufficient.

**Comment by LKmubihei** [comment]
Yes, that's what I did
![image](https://user-images.githubusercontent.com/114295414/228225589-38df7c7c-d6b1-403b-aac2-aef445a891eb.png)

**Comment by jaybrecht** [comment]
Okay thanks just checking. We will run some tests and try to replicate the issue on our side.

**Comment by jaybrecht** [comment]
I was able to replicate the issue using your configuration. We will try to fix this soon.

**Comment by LKmubihei** [comment]
Has this problem been resolved?

**Comment by zeidk** [comment]
I will push an update today which resolves the issue.

**Comment by zeidk** [comment]
Hello, can you try the branch release_1.2_staging to see if the crash is gone on your side?

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/233644200-fd4eb6ff-e06e-48be-935e-3c34a8e1de89.png)
Still no solution for Gazebo crashes caused by parts falling off

Still no solution for cases where a destination error results in a score of 0

**Comment by zeidk** [comment]
Thanks for the feedback on this. For the score being 0, we managed to solve it by making sure the destination of the AGV is the warehouse before submitting the order. Is your code subscribed to the topic [/ariac/agv{n}_status](https://ariac.readthedocs.io/en/latest/competition/ros_communication.html#communications-topics)?

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/233755930-9b6be666-4501-4380-ac59-bdc88b76bf57.png)
I have subscribed the topic [/ariac/agv{n}_status](https://ariac.readthedocs.io/en/latest/competition/ros_communication.html#communications-topics)  .   When I tested the original kitting.yaml, I was able to identify the correct destination. But when I change the order to the following, there is an exception . I change agv_number and quadrants in that order
 orders:
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 2
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 2
        - type: 'pump'
          color: 'purple'
          quadrant: 3

**Comment by LKmubihei** [comment]
By confirming that the AGV has arrived before submitting the order, I have solved this problem.Thank you

**Comment by zeidk** [comment]
I have updated the test competitor to handle this as well. Will push everything once I fix the gazebo crash.

**Comment by zeidk** [comment]
Hello, can you give it another try:

- Branch: release_1.2_staging
- To check that gazebo does not crash, use the trial faulty_gripper_sample.yaml with the test competitor.
- To check the bonus is properly computed, use any trial that has kitting.
- The test competitor has also been modified to submit a kitting order only when the AGV reaches the warehouse.

**Comment by LKmubihei** [comment]
The  dropping still causes Gazebo to crash
![image](https://user-images.githubusercontent.com/114295414/233826234-c185fad0-efa2-464c-8712-0d50dd28947b.png)

**Comment by LKmubihei** [comment]
I might have downloaded the wrong version before, now the falling parts won't cause crashes anymore.

However, when I tested the human_kitting.yaml task, I encountered a problem. After submitting the second order, there was an issue with the recognition, and it failed to identify the parts, resulting in a problem with the scoring.
![image](https://user-images.githubusercontent.com/114295414/233843227-1c5399c2-97ba-4884-b071-6722f416ebf0.png)

![image](https://user-images.githubusercontent.com/114295414/233843265-c02411f8-0b41-4c84-9de5-e774249dd3bf.png)

![image](https://user-images.githubusercontent.com/114295414/233843282-ede5bfd5-60e6-4349-bfb1-48660686e314.png)

**Comment by zeidk** [comment]
The picture you posted does not seem to match the orders in human_kitting.yaml.
For the order on AGV4, the blue battery should be in quadrant 1 and the purple pump should be in quadrant 2. Based on the picture you used quadrants 3 and 4.
For the order on AGV1, the blue battery should be in quadrant 3 and the purple pump should be in quadrant 4. Based on the picture, you used quadrants 1 and 2.
This is why the quality check service reports missing_part=True

Can you check the parts you placed are in the actual quadrants>

**Comment by LKmubihei** [comment]
Thank you, indeed it is an issue of the tray and the parts not matching.

But in all of my previous correct actions, I have been rotating the tray 180 degrees, which is why you may have thought my parts were completely reversed. This can actually earn points, so this kind of action should be allowed, right?

**Comment by zeidk** [comment]
Ok, I understand. Yes you are correct, this should award you points as well.

**Comment by LKmubihei** [comment]
Ok,Thak you

**Comment by LKmubihei** [comment]
When testing in docker, sometimes the scoring system is not accurate. Specifically in the tests "drop_challenge-yaml "," human_kitting.yaml","kitting_combined.yaml" all had similar problems
![image](https://github.com/usnistgov/ARIAC/assets/114295414/c4c0cd6c-820b-4292-8204-ba5e3d0251a6)

**Comment by zeidk** [comment]
Hello, we will push a new docker image tomorrow and will let you know when it's ready. Please try with the new version and let us know if the problem still persists.

**Comment by jaybrecht** [comment]
The updated image was pushed to docker hub this morning. Can you run the trial(s) and see if the issue is resolved?

**Comment by LKmubihei** [comment]
Ok,the score is correct now
