### ISSUE TITLE
Gazebo crashes for parts on floor

### ISSUE THREAD

**Issue by jaybrecht** [usnistgov/ARIAC#218]
Appears to be a problem with the object disposal plugin with the floor model.

**Comment by jaybrecht** [comment]
@LKmubihei I just tested dropping each of the parts using the current release and I did not see any crashes. Please test on your end and let me know if the current release fixes this issue for you.

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/230431086-e5e1d653-2c63-44d5-83da-69997cadcc75.png)
Dropping parts still causes Gazebo to crash, as shown in the terminal. Does your configuration require loading some online models? Some URLs are inaccessible to me.

**Comment by jaybrecht** [comment]
Yes this issue seems to be related to the agent which is for the human. When you get the human working see if this bug still happens.

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/232366318-2a52b8a4-a0bf-4e33-b5ee-bd66271195bb.png)
This issue still occurs where the dropping of parts causes Gazebo to crash.

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/232415666-9c51b5d0-cf4a-489c-806b-5dd47632a1b5.png)
Sometimes this also happens when a part is dropped from an AGV due to instability
