### ISSUE TITLE
human move

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#221]
I find human does not move in the human challenge.but after  using  "ros2 topic echo /ariac_human/joint_states" ,I can see it's output . Does this mean that the Human Challenge is supposed to be like this, or is there a bug present?

**Comment by jaybrecht** [comment]
In order for the human challenge to work properly you need to install java. The updated instructions are in [the documentation](https://ariac.readthedocs.io/en/latest/getting_started/installation.html). Here is the applicable note  
![java_install_note](https://user-images.githubusercontent.com/50928580/230386865-f5b88993-6df7-44bd-b1f5-d3b9f189169e.png)

**Comment by LKmubihei** [comment]
I updated the entire workspace according to the tutorial, but human still does not move in the environment.

**Comment by jaybrecht** [comment]
What trial configuration are you using?

**Comment by LKmubihei** [comment]
human_assembly.yaml

**Comment by jaybrecht** [comment]
I just tested that trial on my machine and it works. Have you run the rosdep install command as well? Also the human does not start until five simulation seconds after the competition is started.

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/230429627-8045818e-2c18-4374-ac16-f14abb9314b8.png)

**Comment by LKmubihei** [comment]
Subscribed topic shows that 'human' is start, but the 'human' does not move.  I can also subscribe to /ariac_human/joint_states.

**Comment by LKmubihei** [comment]
I suspect if it's related to the issue I had in #218, where I couldn't access some websites.

**Comment by jaybrecht** [comment]
Can you try running `sudo apt install openjdk-17-jre` and see if that fixes the issue?

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/230619813-d69454e5-0448-4392-b01a-51d05e3aa5c4.png)
this issue is not fixed ,this situation will always happen

**Comment by LeandroBecker** [comment]
It looks like there is a problem with Java installation, so that our code is not being launched. Let me suggest the following test: please go to the agent folder (ARIAC/ariac_human/agent/) and execute "./gradlew runHelp". This will probably not work, as it looks like that your machine is not properly configured with Java. This command should work once jdk_17 is properly configured (test with "java --version" and "javac --version").

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/230711847-8de697e9-4e66-4289-8d5c-19ee6d52f1d2.png)
![image](https://user-images.githubusercontent.com/114295414/230711857-a1351b23-4106-4b6e-9655-da9a0011956a.png)

**Comment by LKmubihei** [comment]
Do you have any other suggestions?   I will try uninstalling and reinstalling Java

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/230714618-7f3bbc42-7148-441a-8a67-bc592c4da87c.png)
After downloading the dependencies such as org.jason:jason:3.1 from the local repository, this situation occurred.

**Comment by LKmubihei** [comment]
.The "runHelp" task has started and is attempting to connect to ws://localhost:9090. But EXECUTING time is too long ,no response

**Comment by LeandroBecker** [comment]
These are good news, it means that the agent is running fine (everything that is needed is there). Now please:
- Reboot the machine; 
- Double check if the proper java is working;
- Launching "human_assembly" should work fine

In some machines, like mine, it works the first time and does not work a second time - so far I am the only one in the group with such problem. 
To properly work after the first run you must kill the background process that was left there:
- ps aux | grep GradleDaemon
- kill <such_process>

I hope you are all set now. If not, when launching the trial, take a look if the agent process is running: 
ps -aux | grep RunLocalMAS

Please let me know how it goes.

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/230762737-3376165c-6816-42c9-9f19-a6f51854104b.png)

Currently, the 'human' still won't move, as shown in the terminal display when the environment is opened.

![image](https://user-images.githubusercontent.com/114295414/230762906-54e688a0-d389-44bf-b888-b4e675059626.png)

**Comment by LeandroBecker** [comment]
Hello, good morning. Sorry for the delay. I am now fully available to interact and put the human to work ;-)

Your agent is properly loaded, which is good. But the error message in respect to the 'planner_server' is not good and might be the source of the problem. 

Let’s try to “see” what's going on from the human-agent perspective. Therefore let’s enable its console:
On the file ‘~/ariac_ws/src/ARIAC/ariac_human/agent/logging. Properties’, uncomment line 7 and comment line 8. 
Then rebuild everything (_colcon build_) and run again the human_assembly challenge. The console should be there. Please send some prints of that.

Remember that after launching the trial, you must publish the topic for the human to start moving:
_ros2 topic pub /ariac/start_human std_msgs/msg/Bool '{data: true}' --once_

**Comment by LKmubihei** [comment]
![image](https://user-images.githubusercontent.com/114295414/231391941-f0abaae5-25e8-4120-81af-bc2561c9451a.png)


![image](https://user-images.githubusercontent.com/114295414/231392215-9043c1eb-796c-4434-8ba0-e0349ce54137.png)

**Comment by LKmubihei** [comment]
The first image shows the result after running the challenge, and the second image shows the result after running 'ros2 topic pub /ariac/start_human std_msgs/msg/Bool '{data: true}' --once'.

**Comment by LeandroBecker** [comment]
Thanks for the feedback. This shows that the agent is properly running. So let's focus on the planner_server issue. I suggest the following: 
1) open a new terminal and source ROS2
2) goto ariac_ws folder
3) delete everything except the 'src' folder
4) rebuild with colcon build
5) Check for updates: apt update
6) Adjust dependencies: rosdep install --from-paths src --ignore-src -r -y
7) rebuild: colcon build
8) source the project: source install/setup. bash

After this run the trial again and let's see if the problem is over

**Comment by LKmubihei** [comment]
The problem still exists
I have tried  your method twice, but the human still won't move.
![image](https://user-images.githubusercontent.com/114295414/231630651-04d9974d-897e-4efc-ba1c-a67a0984043a.png)

**Comment by LeandroBecker** [comment]
Thanks for the feedback. Let's do another test. Once the 'human_assembly' trial is up, please execute the following in a terminal:
ros2 topic pub /ariac_human/goal_position geometry_msgs/msg/Point "{x: -10.0, y: -4.0, z: 0.0}" --once

If it still does not move after a while, cancel everything and please send here some ROS logs:
1) $HOME/.ros/log/**latest-folder**/launch.log
2) $HOME/.ros/log/controller_server_*.log
3) $HOME/.ros/log/planner_server_*.log
4) $HOME/.ros/log/bt_navigator_*.log

**Comment by LKmubihei** [comment]
Thank you, I found the issue by checking the logs and solve it .now, the human can move . 
![image](https://user-images.githubusercontent.com/114295414/231721932-361bc476-1eaf-4322-8985-2a200f2771a7.png)

It was the 'ModuleNotFoundError: No module named 'nav2_simple_commander''.So, I followed this tutorial " 
https://navigation.ros.org/build_instructions/index.html" to install nav2, which made my workspace too large. 

![image](https://user-images.githubusercontent.com/114295414/231722656-1fd010ac-5429-4fa1-a1f9-255a4d835818.png)
Do you have any suggestions for a better solution?"

**Comment by LeandroBecker** [comment]
In my installation I did not add that to my workspace, I simply executed the following:
sudo apt-get install ros-galactic-nav2-simple-commander

**Comment by LKmubihei** [comment]
ok, I was able to fix it after using this command as well

**Comment by akashjinandra** [comment]
I am also not able to get the human to move, but I get this error:  

[1681685657.981517261] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Lookup would require extrapolation into the past.  Requested time 1.395000 but the earliest data is at time 1.601000, when looking up transform from frame [base_link] to frame [map]

**Comment by LeandroBecker** [comment]
Dear Akash, if you follow the above discussion, you'll see that the Human was not moving given 2 problems: 
1) Java was not properly installed;
2) nav2-simple-commander was missing.

Tips on how to solve these two issues are given above. If you are sure these are not your problems, please send over here the following ROS logs:

$HOME/.ros/log/**latest-folder**/launch.log
$HOME/.ros/log/controller_server_*.log
$HOME/.ros/log/planner_server_*.log
$HOME/.ros/log/bt_navigator_*.log

**Comment by akashjinandra** [comment]
Got it working, i didn't realize I was building in correctly, using --symlink-install in order to save time on not having to build every time I change a yaml file. and forgot to chmod +x the python files inside the ariac_human package.

**Comment by LeandroBecker** [comment]
That's great.
