### ISSUE TITLE
order  valid_id

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#222]
Does this mean that each order can only invoke quality check once, but when I use it in practice, I can invoke the quality check service multiple times
![image](https://user-images.githubusercontent.com/114295414/230710763-993720ba-2d32-43c0-8449-3d0f363a4dd6.png)
The valid_id is still True
![image](https://user-images.githubusercontent.com/114295414/230710845-5c45ebda-85ca-4983-9a66-189344c158aa.png)

**Comment by LKmubihei** [comment]
Oh, Does it mean that orders that have passed quality check will be considered invalid?

**Comment by zeidk** [comment]
This means that if you call this service with a wrong order ID then valid_id returns false. Let's say you have an order with the ID "MH300" and you call this service by passing the ID "MH301", then valid_id returns false since "MH301" does not exist.

**Comment by LKmubihei** [comment]
I understand what you mean, but what I want to ask is whether the quality check service can only be called once.

**Comment by zeidk** [comment]
This is correct, you can call this service multiple times.

**Comment by LKmubihei** [comment]
ok,thanks

**Comment by anthonydowns** [comment]
Closing this issue as complete
