### ISSUE TITLE
high priority order question on same agv

### ISSUE THREAD

**Issue by akashjinandra** [usnistgov/ARIAC#228]
Hello, is it possible that a high priority order will be on the same agv as one of the lower priority orders that are still running? For instance you just placed a part on agv2, can the high priority order also be on agv2? in which case the user would have to take off the old parts and put new ones on?

**Comment by zeidk** [comment]
Hello, although technically possible, this  will not happen. Competitors will not  reuse the same AGV for multiple Orders.

**Comment by anthonydowns** [comment]
Closing this issue as complete
