### ISSUE TITLE
human size and distance question

### ISSUE THREAD

**Issue by akashjinandra** [usnistgov/ARIAC#229]
Hello,

In the agility challenge it mentions: The goal of this challenge is to test whether or not the CCS is capable of ensuring the safety of humans on the shop floor. The ceiling robot has to keep a safe distance from the human at any time. If the ceiling robot gets too close to the human, the human will be considered to be in danger and two events happen:

What is the distance the ceiling robot must be away in order for it to be considered safe?

Also is there an approximate size of the robot that we can use for reference?

**Comment by akashjinandra** [comment]
Another thing I noticed is that the human most of the time ends up teleportation away and not disabling the robot. With the java gui turned on I see this: 
![image](https://user-images.githubusercontent.com/22859817/233264627-a153f80d-a1b5-4bfb-98cb-4f4100a65770.png)

**Comment by LeandroBecker** [comment]
Hi back,

Your print shows that the human was teleported for being too close to the AGV. The maximum distance they can reach is 2.1, bellow that the human is teleported without disabling the robots - disabling only occurs if the human reaches the safe distance from the ceiling robot.

The safe distance from the ceiling robot is variable, depending on the speed of both human and ceiling robot. In the documentation we provide the formulae used to calculate such distance: 
https://ariac.readthedocs.io/en/latest/competition/challenges.html#human

**Comment by anthonydowns** [comment]
Closing this issue as I believe it is complete?
