### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#243]
![image](https://github.com/usnistgov/ARIAC/assets/114295414/4f97f453-21f0-428e-b7be-d95171086658)
I used the “tf_transformations” , but it may be outdated, which resulted in the inability to install it.

**Comment by jaybrecht** [comment]
Please post any questions about automated evaluation [here](https://github.com/usnistgov/ARIAC/discussions/242). 

I tried `pip3 install tf_transformations` locally and got the same error. Are you sure that is the correct name for the package?

**Comment by LKmubihei** [comment]
Yes, I should use the command 'sudo apt install ros-galactic-tf-transformations' to install it.
