### ISSUE TITLE
Human chanllenge

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#245]
When tested in docker, the human did not move

**Comment by AravindaDP** [comment]
Not only docker, Even using local setup did not worked for human_kitting trial file provided.

**Comment by LeandroBecker** [comment]
Besides the docker detail, I recommend going through the issues #221 and #229 for clarifying how to make humans to move.

**Comment by AravindaDP** [comment]
OK. In local setup when human_control_node.py was made executable issue got resolved.

**Comment by LKmubihei** [comment]
The human did not move in the latest docker in my test

**Comment by LKmubihei** [comment]
https://github.com/usnistgov/ARIAC/assets/114295414/2807821d-e528-4bea-9b8a-223728a51106

This video shows human_assembly test,the human do not move in the tset

**Comment by LKmubihei** [comment]
Is the problem being solved?
