### ISSUE TITLE
For flipped part (pump) vacuum_gripper_plugin detects attachment but gazebo do not pick up object.

### ISSUE THREAD

**Issue by AravindaDP** [usnistgov/ARIAC#252]
Following is logged in output but pump is not picked up in simulation as usual.
```
[gzserver-2] [INFO] [1684679930.392990118] [floor_vacuum_gripper_plugin]: Picking object
```

**Comment by jaybrecht** [comment]
Can you recreate this and record your screen for reference? If the simulation posts this message than the joint between the robot and the part has already been established so it should be attached at this point.

**Comment by jaybrecht** [comment]
Closing in favor of #251

**Comment by AravindaDP** [comment]
Actually it seems the issue is somewhere else. It seem to be incorrect planning scene handling in competitor code for the case without considering that part links are on bottom of the part instead in the middle.

**Comment by jaybrecht** [comment]
The part links are on the bottom of the part though.
