### ISSUE TITLE
Result feedback

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#253]
The announcement says that the results of the qualifiers will be fed back to Google Drive on May 23, but I haven't received any feedback yet

**Comment by anthonydowns** [comment]
Team Reaper, please check to make sure that you have your files in your folder. It looks empty on our end. Nothing for us to run.

**Comment by LKmubihei** [comment]
![image](https://github.com/usnistgov/ARIAC/assets/114295414/9bd29198-10e0-40d6-8e0d-b036dc26fa1f)
I have uploaded the yaml file to Google Driver

**Comment by jaybrecht** [comment]
I see the submission now, I am not sure why we couldn't see it before. I am running the qualifier trials for your team now. It does seem like you are not ending the competition after all orders are submitted. This is not necessarily a problem the program will run until the trial time limit but it would be better for you to end the competition through the ROS service when your program finishes all orders.

**Comment by AravindaDP** [comment]
Team Runaround Robotics also have files in drive since 23rd (Note that we also have pre-build script in competitor_build_scripts folder)

**Comment by LKmubihei** [comment]
![image](https://github.com/usnistgov/ARIAC/assets/114295414/e3150c31-44f9-4aa2-b91e-310c01dbd4d2)
Does Ti mean from the beginning of the competition to the end of the competition? That said, I need to end the competition myself to reduce the time consuming. 
The reason I didn't end the competition before was that I didn't know when the order would come, if I end the competition after submitting the first order, but at this time the second order had not been announced. For example, this problem occurs in the human_kitting task.the second order was announced at 60s, but my first order was submitted before 60s

**Comment by jaybrecht** [comment]
@AravindaDP Yes we have run the qualifiers for your submission. The results should be available in the same folder as the submission on Google Drive sometime today. 

@LKmubihei Ti in that case is submission time for the order so it wont affect your score. 

The competition state topic will be changed to ORDER_ANNOUNCEMENTS_DONE when all orders have been announced. Your system should wait until this is set before ending the competition. 

![Screenshot 2023-05-25 085218](https://github.com/usnistgov/ARIAC/assets/50928580/c0d2e7f6-3304-4c67-a1b9-26947f0aa63a)

**Comment by LKmubihei** [comment]
Ok,I understand

**Comment by AravindaDP** [comment]
I see some files with high level results. Will it be the same level of information we'll be receiving in the finals as well?
1. Can we have full roslog/console output?
2. Will it be possible to have gazebo state log and script that can be used to replay similar to last year?

It's OK if you don't have facility to provide these at the moment and looking forward to implement it for the final scoring.

**Comment by LKmubihei** [comment]
Hi, the results of this year's competition seem to be a bit slow to be released, I was wondering when the results will be announced?

**Comment by zeidk** [comment]
Hello,

We will announce the results as soon as we have the results from the human judges. Hopefully next week. We apologize for the delay.
