### ISSUE TITLE
Docker image outdated?

### ISSUE THREAD

**Issue by AravindaDP** [usnistgov/ARIAC#255]
Started getting bunch of errors on docker image build. Could it be outdated and no longer able to clone competitor repo or install packages from apt due to this?

For example with nist_competitor sample yaml
```
Running nist_competitor.yaml
Cloning into '/home/ubuntu/ariac_ws/src/nist_competitor'...
fatal: unable to access 'https://github.com/jaybrecht/nist_competitor.git/': Could not resolve host: github.com
```

**Comment by jaybrecht** [comment]
Could you try updating the token with the latest from step 9 of Testing the Automated Evaluation on this page: https://ariac.readthedocs.io/en/latest/automated_evaluation/automated_evaluation_overview.html

**Comment by AravindaDP** [comment]
It is already in that latest token. Besides same error for our own repo. And also apt-get update and apt-get installs inside docker is also causing (different to above though) errors. Not sure if it's a problem of my local docker setup but it was working without any issues earlier. May be some certificate/key file expired in underline docker image?

**Comment by jaybrecht** [comment]
I just tested it on a new machine and everything worked properly for me so I don't think the issue is with the image. The error above with GitHub the apt-get errors seems like the container is not connected to the network properly.

**Comment by AravindaDP** [comment]
Yes you are correct. After a reboot of system it got resolved. Closing the issue
