### ISSUE TITLE
updated order priority bonus?

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#27]
Do updated orders not get the x3 priority order bonus?  Didn't happen for qual_1_a.

**Comment by zeidk** [comment]
I will check the script on this one and will report back.

**Comment by zeidk** [comment]
Hi Dan, are you talking about updated order or high priority order (interruption)? Did you get a chance to try qual_a_3.yaml where there is an order interruption?

**Comment by dan9thsense** [comment]
I was asking if the updated orders get a 3x priority order bonus.  When a new order that is not an update comes in, that gets the 3x bonus as it should.  I was wondering if the updated orders also get a x3 bonus.

**Comment by zeidk** [comment]
Updated orders will not get a priority bonus. We may implement this for next year but it will be less than x3 for sure.

**Comment by dan9thsense** [comment]
OK, thanks for the clarification.
