### ISSUE TITLE
seg fault from plan_and_execute method

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#289]
Calling the tutorial 10 competition interface method _plan_and_execute (generally without plan_parameters) multiple times eventually (after about 6 calls) generates a segmentation fault.  There is no additional information in the logs about what generates it.

process has died [pid 41695, exit code -11,

**Comment by jfernandez37** [comment]
Here is the link to the new tutorials and the documentation for it. The tutorial you are running is out of date. Hopefully, these work better.
Tutorials: [https://github.com/usnistgov/ARIAC_tutorials.git](https://github.com/usnistgov/ARIAC_tutorials.git)
Documentation: [https://pages.nist.gov/ARIAC_docs/en/latest/tutorials/tutorials.html](https://pages.nist.gov/ARIAC_docs/en/latest/tutorials/tutorials.html)

**Comment by dan9thsense** [comment]
OK, thanks for the update.
