### ISSUE TITLE
pump goes crazy when trying to attach

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#293]
When slowly lowering down to a battery, things work fine, but slowly lowering onto a pump makes it go flying all about as soon as contact is made.  Perhaps there is a collision bug?

**Comment by jaybrecht** [comment]
PR #288 added some changes that should make assembly and part picking more reliable/stable. Are you working with the most recent version? 

Also are you using the tutorials package (python) or the test competitor (c++)?

**Comment by dan9thsense** [comment]
Good call.  Pulling the new version fixed the problem.

**Comment by jaybrecht** [comment]
Glad that it is fixed. What is currently on the ariac2024 branch (renamed from ariac2024_dev) has all of the changes we are planning for this year's competition . We will add any bug fixes necessary but there shouldn't be any more large changes or features.
