### ISSUE TITLE
ariac-docker repository

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#3]
The [tutorial for preparing submissions](https://github.com/osrf/ariac-docker/blob/master/README.md) links to an osrf repository that was used last year.  Is that still valid for this year?  If not, is there an updated repository for ariac-docker?

**Comment by Pavel-P** [comment]
No, we still need to update that repository to use this year's docker images, but once that's done we'll update the documentation and let you know.

**Comment by zeidk** [comment]
We will update the documentation on docker by the end of this week. We will also try to document the other parts of the wiki as well.

**Comment by dan9thsense** [comment]
Did this get done?  The docs still point to the osrf repo.  I'm concerned that there is only a month left until the qualifiers and it often takes some time to get docker stuff working correctly.

**Comment by zeidk** [comment]
Hi Dan,
we are in discussion with OSRF about the docker image to use. I will update the webpage and reply here as soon as I hear from them.

thank you,

zeid

**Comment by zeidk** [comment]
Just an update that the docker image will be pushed tomorrow. The tutorial on automated evaluation will be updated accordingly.

**Comment by dan9thsense** [comment]
I couldn't find the new image; looks like the tutorial still points to the old pages.

**Comment by zeidk** [comment]
We are working on the dockerhub account. I will update this thread when this gets fixed.

**Comment by zeidk** [comment]
Docker images were pushed on dockerhub and bash scripts were updated.

Please see wiki/documentation/automated_evaluation.md and wiki/tutorials/automated_evaluation.md

Closing this ticket for now. Open a new one if any issue arises with automated evaluation.
