### ISSUE TITLE
cages around pump parts

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#304]
When taking camera images (and when looking closely) the pump parts are surrounded by cages with clear walls and black edges, presumably to show where the gripper attaches.  Will those cages show up camera images during headless docker runs?  If not, how to suppress them in gui runs?

**Comment by jaybrecht** [comment]
The "cages" are considered part of the pump. The docker runs will not be run headless, they will be run with the gz_client running so there should be no difference in the images between running locally and running in docker. The evaluation in docker uses x11 window forwarding to show the gazebo GUI.

**Comment by dan9thsense** [comment]
sounds good, thanks for the clarification
