### ISSUE TITLE
colcon build fails due to cv_bridge

### ISSUE THREAD

**Issue by endre90** [usnistgov/ARIAC#305]
#### OS: 
Ubuntu 22.04
#### ROS2: 
Humble (binaries)
#### Issue: 
```
~/ariac_ws/src/ARIAC/ariac_sensors/src/ariac_camera_plugin.cpp:18:10: 
fatal error: cv_bridge/cv_bridge.hpp: No such file or directory
   18 | #include <cv_bridge/cv_bridge.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/AriacCameraPlugin.dir/build.make:76: CMakeFiles/AriacCameraPlugin.dir/src/ariac_camera_plugin.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/AriacCameraPlugin.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< ariac_sensors [2.01s, exited with code 2]

Summary: 7 packages finished [4.17s]
  1 package failed: ariac_sensors
  1 package had stderr output: ariac_sensors
```
#### Fix that worked for me:
Replace line `18` in `ariac_camera_plugin.cpp`:
```
#include <cv_bridge/cv_bridge.hpp> -> #include <cv_bridge/cv_bridge.h>
```

**Comment by 130s** [comment]
If you're using Ariac 2024 branch (which you didn't clarify at the time), that depends on  ROS2 Iron, not Humble. `vision_opencv` that includes `cv_bridge` pkg has deprecated `.h` headers in ROS2 Iron https://github.com/ros-perception/vision_opencv/issues/262#issuecomment-1760609581 so you seeing breakage "makes sense". Solution would be to switch to ROS2 Iron.

**Comment by endre90** [comment]
Hi, thanks for your quick answer. I assumed that Humble can work too. I managed to run the simulation with Humble anyway, just a few minor changes. Best Regards.
