### ISSUE TITLE
what is "direction?"

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#308]
The orders for assembly task specify position and orientation for a part.  What does "direction" mean?  The documentation mentions that it is a "principal axis" for the part, but it seems the part's location is already fully specified by position and orientation.

**Comment by jaybrecht** [comment]
The install direction field is a unit vector that describes which direction the part should be installed relative to the assembly insert frame. For example since the pump needs to be installed "down" the vector is [0 0 -1].

**Comment by dan9thsense** [comment]
OK, thanks
