### ISSUE TITLE
setting plan parameters

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#311]
In the tutorial code, under plan_and_execute, there is an option to include plan_parameters.  I think this allow things like setting the goal_position_tolerance.  However, I have been unable to find an example of the form of how that parameter is passed when calling plan_and_execute.

Here is an example call without a "single_plan_parameters" entry:

```
plan_and_execute(self._robots, self._ceiling_robot, robot_type="ceiling_robot")
```

Here is the relevant section of "plan_and_execute"

```
elif single_plan_parameters is not None:
     plan_result = planning_component.plan(single_plan_parameters=single_plan_parameters)
```

Is there an example of calling with the "single_plan_parameters"  option?

```
single_plan_parameters= ?
```
What goes here to, for example, set the joint tolerance for the goal?
What other parameters are allowed, e.g., can you set joint speed?

plan_and_execute(
    self._robots, 
    self._ceiling_robot, 
    robot_type="ceiling_robot", 
    single_plan_parameters=single_plan_parameters
)
```

**Comment by jfernandez37** [comment]
Both single_plan_parameters and multi_plan_parameters are to select the planning pipeline or pipelines you would like to use. multi_plan_parameters allows you to execute the planning pipelines in parallel and it chooses the best one. There is a bit more information about it in the moveit_py documentation: [https://moveit.picknik.ai/main/doc/examples/motion_planning_python_api/motion_planning_python_api_tutorial.html#understanding-planning-parameters](https://moveit.picknik.ai/main/doc/examples/motion_planning_python_api/motion_planning_python_api_tutorial.html#understanding-planning-parameters)

**Comment by dan9thsense** [comment]
Yes, I saw that page and noted in particular:

```
multi_pipeline_plan_request_params = MultiPipelinePlanRequestParameters(
        panda, ["ompl_rrtc", "pilz_lin", "chomp", "ompl_rrt_star"]
)
```
But do not know how to do this for a single plan.  This page shows the planning component class reference but only lists mutlipipeline.
https://docs.ros.org/en/noetic/api/moveit_ros_planning/html/classmoveit__cpp_1_1PlanningComponent.html

**Comment by dan9thsense** [comment]
The values that I would like to set are:

  max_velocity_scaling_factor
  max_acceleration_scaling_factor

I see these set in the planning config file and can change them there but still don't see how to get the newly created or modified pipeline selected.  Also "pipeline_names" in the config file names "ompl" but that does not correspond to any of the listed ones, such as "chomp_b"

**Comment by jfernandez37** [comment]
The single_plan_parameters parameter type is `moveit.planning.PlanRequestParameters`. This can be included using:

```python
from moveit.planning import PlanRequestParameters
```

The snippet below shows how to move the floor robot to the home position with modified velocity and acceleration factors:

``` python
# Set the start state and goal state for the robot
with self._planning_scene_monitor.read_write() as scene:
    self._floor_robot.set_start_state(robot_state = scene.current_state)
    self._floor_robot.set_goal_state(configuration_name="home")
   
# Create the plan request parameters 
single_plan_parameters = PlanRequestParameters(self._ariac_robots, "floor_robot")
single_plan_parameters.max_acceleration_scaling_factor = 0.1
single_plan_parameters.max_velocity_scaling_factor = 0.1
single_plan_parameters.planning_pipeline = "ompl"

self._plan_and_execute(self._ariac_robots,self._floor_robot, self.get_logger(), robot_type="floor_robot", single_plan_parameters=single_plan_parameters)
```

**Comment by dan9thsense** [comment]
Thanks, that is very helpful. Where did you find the documentation for this?

**Comment by jfernandez37** [comment]
Unfortunately, we could not find any documentation for this. Using `PlanRequestParameters` was found through reading through the c++ source code and testing.

**Comment by dan9thsense** [comment]
Ah, yes, welcome to the world of ROS 2 and Moveit2.  Thanks for doing the work to figure this out.
