### ISSUE TITLE
Running Tutorial 6 reports an error

### ISSUE THREAD

**Issue by Zhangjiyuan1** [usnistgov/ARIAC#319]
I get the following error when I run the tutorial 6 file:
[ERROR] [1711003524.173501756] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
Sometimes it works successfully, but most of the time it still gives an error like the one written above.I don't know what causes it to be good and bad.

**Comment by jaybrecht** [comment]
This error can be ignored. It is for MoveIt but will not affect anything for ARIAC.
