### ISSUE TITLE
TF transforms for logical camera duplicated

### ISSUE THREAD

**Issue by stevegray954** [usnistgov/ARIAC#32]
* Logical camera transforms (i.e. world -> camera) are duplicated on `/tf`, since they're already on `/tf_static`
* Transforms for objects seen by logical camera are published one at a time, which is slower than publishing them all at once each update cycle.

Fix and speedup in pull request #31

**Comment by dan9thsense** [comment]
This sounds reasonable, but let's be careful about making changes right before the qual runs.

**Comment by Pavel-P** [comment]
The PR looks good, for the sake of keeping people happy I'll hold off on pulling it in until after quals.

**Comment by stevegray954** [comment]
PR #31 is still valid for 2021.  Please pull it. @zeidk @Pavel-P

**Comment by stevegray954** [comment]
#31 has been merged
