### ISSUE TITLE
 No Google Drive folder received 

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#327]
We didn't receive the Google Drive folder this year . Is it possible to use last year's folder?

**Comment by anthonydowns** [comment]
Hi @LKmubihei I sent out the folders for this year this morning.  If you did not receive a google drive, please check with your team mates and let me know if you all need additional people to have access to your Reaper folder.

**Comment by anthonydowns** [comment]
If you or anyone else needs access to their google folders, please check the email that you registered with and send me an email: anthony.downs[at]nist.gov if you have issues or need additional assistance
