### ISSUE TITLE
No orders announced after the start of the competition

### ISSUE THREAD

**Issue by LKmubihei** [usnistgov/ARIAC#328]
First, I start the environment  'ros2 launch ariac_gazebo ariac.launch.py '
Then I start the competition 'ros2 service call /ariac/start_competition std_srvs/srv/Trigger'.but  there is no order is announced in the termial

**Comment by jfernandez37** [comment]
Hello. I tried to replicate the issue you are running into, but I could not. Could you tell me a bit more about your setup? What version of ROS are you running? Thanks

**Comment by jaybrecht** [comment]
@LKmubihei Were you able to solve this issue?

**Comment by LKmubihei** [comment]
There is no order release on my newly installed ubuntu22 system, my ROS2 version is iron, but I can run it fine in docker
![Screenshot-1](https://github.com/usnistgov/ARIAC/assets/114295414/c49fbb22-dbb9-4161-8159-4182ad494fcf)

**Comment by LKmubihei** [comment]
![Screenshot-2](https://github.com/usnistgov/ARIAC/assets/114295414/bff73fd5-9a39-4879-8301-fedd5c52e4de)
After I terminate the program , it displays there is no order announced

**Comment by LKmubihei** [comment]
For reasons unknown, when I reinstalled ARIAC again, it could announce orders normally!

**Comment by jaybrecht** [comment]
Glad that it worked after a new install. We were unable to replicate the issue so I think it must have been an issue with your local configuration. Let us know if you run into any other issues.
