### ISSUE TITLE
details on github release

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#339]
Can you provide details on how the github release should be done? For example, should there be a specific tag? Does it need its own personal access token?

**Comment by jaybrecht** [comment]
Yes, there should be a tag created when you create the release. That is what you should use in the "tag" line item in the yaml file. 

These instructions show how to create a release on github: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

This does not require a separate PAT. It essentially works as a branch on your repository.

**Comment by dan9thsense** [comment]
Thanks, working now.
