### ISSUE TITLE
parseURDF error

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#342]
This error is repeated over and over when the sim starts and then occasionally throughout.  Does not seem to harm anything, but should probably be addressed.

```
[gzserver-1] Error [parser_urdf.cc:3183] Unable to call parseURDF on robot model
[gzserver-1] Error [parser.cc:488] parse as old deprecated model file failed.
[gzserver-1] Error:   Could not find the 'robot' element in the xml file
[gzserver-1]          at line 109 in ./urdf_parser/src/model.cpp

```

**Comment by jaybrecht** [comment]
Yes, this is a known error and has to do with the gazebo state log generation which is used for trial playback. You can see that if you turn the record_state argument to false this error goes away. This appears to be a gazebo bug not an ARIAC bug from what I can tell and like you mentioned I have not seen  it cause any other issues than the log errors.
