### ISSUE TITLE
OMPL error

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#346]
The latest pull generates an error when planning a trajectory for a pose. Pretty much wipes out all pose moves. The same competitor code base works OK with a sim code base compiled on April 12.

```
[moveit.ompl_planning.planning_context_manager]: OMPL encountered an error: The fraction of the extent must be larger than 0 and less than 1
```

**Comment by jaybrecht** [comment]
I can't think of any changes that have been made that would affect MoveIt or OMPL. Are you using the default moveit_config package or have you made modifications? Looking at this error it seems like it may have to do with the parameter `longest_valid_segment_fraction` as mentioned [here](https://github.com/moveit/moveit/issues/1297). That is defined for each of the planning groups [in this file](https://github.com/usnistgov/ARIAC/blob/ariac2024/ariac_moveit_config/config/ompl_planning.yaml#L78).

**Comment by dan9thsense** [comment]
Good call. MoveIt updated at the same time. Reverting to the previous version of MoveIt solved the problem. Sorry to bother you.
