### ISSUE TITLE
criteria for being in a quadrant

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#347]
When a part gets placed on a tray, what determines if it is "in a quadrant?" Does the entire part have to be within the black lines that designate a quadrant on the tray? Is it sufficient to have the center of the part within the lines?

I've noticed that when a part is a bit outside the lines, then the scoring says the part is in the quadrant but it is flipped, even though it is not flipped. Quality control also returns flipped part = True when a part is crossing the boundary by a bit.

Here is an example with a battery that was not flipped but was about 10% outside the boundary line.
Quadrant: 3
  Score: 0
  Correct part type: yes
  Correct part color: yes
  Faulty part: no
  Flipped part: yes

**Comment by dan9thsense** [comment]
For example, with no flipped parts used, when the first battery picked was placed in quadrant 3, the quality sensor said it detected no faults.  When the second battery picked was then placed in quadrant 2, the quality sensor said it detected a flipped part in quadrant 3

![image](https://github.com/usnistgov/ARIAC/assets/1042607/d62904b4-4bab-4e33-a340-3d733a00a091)

Here is the scoring:
[gzserver-1] 	Quadrant: 2
[gzserver-1] 		Score: 3
[gzserver-1] 		Correct part type: yes
[gzserver-1] 		Correct part color: yes
[gzserver-1] 		Faulty part: no
[gzserver-1] 		Flipped part: no
[gzserver-1] 	Quadrant: 3
[gzserver-1] 		Score: 0
[gzserver-1] 		Correct part type: yes
[gzserver-1] 		Correct part color: yes
[gzserver-1] 		Faulty part: no
[gzserver-1] 		Flipped part: yes

**Comment by jaybrecht** [comment]
To answer the first question, it should not matter where the part is within the quadrant as long as the center of the part is within the bounds of the quadrant. If you are curious this is the [section of code that determines which quadrant a part is in](https://github.com/usnistgov/ARIAC/blob/ariac2024/ariac_plugins/include/ariac_plugins/ariac_common.hpp#L2229-L2239). 

As for the flipped part issue, yes it seems that there was a bug in our flipped part detection that was misidentifying whether a part was flipped when moved sufficiently far away from the center of the tray. We have implemented a fix and a pull request will be made shortly. Thank you for detecting this issue.

**Comment by dan9thsense** [comment]
Thanks for addressing the issue.

**Comment by dan9thsense** [comment]
Will this be merged at least some days before finals are due? The bug makes testing very difficult because it identifies parts on the AGV as flipped when they are not. That causes the flip code to run, which makes the part actually flipped. That messes up the scoring and that means that a lot of trials fail when they should pass.

**Comment by dan9thsense** [comment]
I realized that since I'm not using Docker for testing, I don't need the image updated. I switched to the branch with the changes and, so far, it is working OK.
Closing the issue for now.
