### ISSUE TITLE
qual_a_3 is missing pulley parts

### ISSUE THREAD

**Issue by stevegray954** [usnistgov/ARIAC#38]
From the description, `qual_a_3` should have a pulley to be flipped - and the order is looking for a red pulley.

However, there are no pulleys - only gears and gaskets.  I think one of the blue gear areas - either on the shelf or bin - should be a red pulley.

**Comment by stevegray954** [comment]
Check out PR #39 -- I changed the blue gears in the bin to be red pulleys.

**Comment by zeidk** [comment]
Thanks, will take care of some issues today including this one.

**Comment by dan9thsense** [comment]
I just saw this today.  Please do not change the qual files.  I saw that there were no pulleys in qual_a_3 and assumed that it was an example of "not enough parts."  I already submitted code for the qualifiers (within the original April 6th to 10th window) and do not have time right now to revise it.  I know I sound like a broken record here, repeating myself, but please don't make late changes.

**Comment by stevegray954** [comment]
I had updated qual_a_3 to match the description [here:](https://github.com/usnistgov/ARIAC/blob/master/wiki/qualifiers/qualifier_scenarios.md#part-a-trial-3)
The description says that a pulley needs to be flipped, which made it odd there were no pulleys.
I'm fine with reverting, but then the description should change.

**Comment by zeidk** [comment]
Dan, your code will be tested against **qual_b** files which you do not have access. **qual_a** files are meant for participants to try their system and whatever you submitted will not be tested using any **qual_a** files. As long as your system deals with flipped parts then you should be good.

**Comment by dan9thsense** [comment]
Oh, i thought the quals used both the qual_a and the qual_b scenarios to generate a score for 6 trials.  It only uses qual_b?

**Comment by stevegray954** [comment]
Agreed, in previous years, the quals used both 'a' and 'b' scenarios.

**Comment by dan9thsense** [comment]
Can we get an answer to this question (Is qual_a used for the qualifiers?) ?  It's pretty important for the qualifiers.
