### ISSUE TITLE
Collision filter causing massive slowdown

### ISSUE THREAD

**Issue by stevegray954** [usnistgov/ARIAC#4]
Lifting a single part is giving me a speed drop from 0.98x to 0.11x.  Until the part has been resting long enough that Gazebo suspends collision checking on it (i.e., you don't see the visualized contacts anymore), the sim speed remains very low.

[Video on Youtube](https://youtu.be/LZqKVDVQfMs)

Check out the real time factor on the bottom.

**Comment by stevegray954** [comment]
I had moved the gear to another location, but I can confirm this happens if you just lift it above the bin it starts in.

**Comment by stevegray954** [comment]
On further investigation, issue is caused by `libROSAriacTaskManagerPlugin.so`
(I removed lines 344-416 from `nist_gear/worlds/ariac.world.template` and the slowdown is gone)

**Comment by stevegray954** [comment]
Worth noting that neither before nor after the fix was the system recognizing contact between the arms, because they are allowed to pass through eachother.

**Comment by stevegray954** [comment]
Workaround is present as PR #7

**Comment by Pavel-P** [comment]
Thanks for taking a thorough look at this. As a side note, we hadn't updated the collision filter to use the "left_" and "right_" prefixes for the link names, which was contributing to the slowdown a lot. But even after fixing that your approach stills seems to be noticeably faster, so I'll go forward with the PR.
