### ISSUE TITLE
Gasket part is requested to be flipped (qual_a_2)

### ISSUE THREAD

**Issue by avidacs** [usnistgov/ARIAC#48]
The wiki states that "Only the pulley_part will ever be requested to be flipped." In contrast, gasket part is required to be flipped as well in qual_a_2.yaml:

order_part3: gasket_part_red

order_0:
     products:
       part_3:
        type: order_part3
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: ['pi', 0, 0]
 
Please clarify, what is to be expected in the challenges? Thanks in advance!

**Comment by zeidk** [comment]
Good catch. First of all, qual_a_2 does not require part flipping, as described in the header of the file and on this page https://github.com/usnistgov/ARIAC/blob/master/wiki/qualifiers/qualifier_scenarios.md
Moreover, you are correct, only pulley parts need to be flipped.

Thanks
