### ISSUE TITLE
collisions penalty

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#49]
I know that the order score is zero if the robot contacts itself or a dynamic obstacle.  However, there does not seem to be any penalty for contacting structures such as shelves or the walls of the conveyor belt or the AGVs.  Is that correct behavior?

**Comment by zeidk** [comment]
Yep, this is correct. The wiki on [scoring](https://github.com/usnistgov/ARIAC/blob/master/wiki/documentation/scoring.md) (see **COL** under **Performance metrics**) states that you will get a 0 if the arms collide with each other, the torso, or a moving obstacle. There is no penalty this year if the arms collide with anything else.

**Comment by dan9thsense** [comment]
OK, thanks for the fast reply.
