### ISSUE TITLE
do the qualifiers use qual_a scenarios?

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#51]
In issue #38 , there was a comment:

Dan, your code will be tested against qual_b files which you do not have access. qual_a files are meant for participants to try their system and whatever you submitted will not be tested using any qual_a files. As long as your system deals with flipped parts then you should be good.

Is this correct?  I thought that both qual_a and qual_b were used for the qualifiers score.

**Comment by zeidk** [comment]
It looks like I replied to this question a while ago in some other threads. We were not planning to use qual_a files during the qualifiers we then decided to replicate the same testing routine as performed in 2019, hence the use of qual_a and qual_b files during the qualifiers testing.
