### ISSUE TITLE
ARIAC2021 sample environment takes a long time to load

### ISSUE THREAD

**Issue by glpuga** [usnistgov/ARIAC#58]
Trying to test the sample environment for ARIAC 2021 using 

> roslaunch nist_gear sample_environment

Takes several minutes of inactivity to load, even when accounting for the time it takes to fetch the models used by the simulation.

The problem seems to be that the configuration file for the environment in `sample_test.yaml` contains two models that are not available to load the current time, `piston_rod_part_blue` and `gear_part_red`.

![Screenshot from 2021-02-21 18-46-10](https://user-images.githubusercontent.com/17802342/108639863-8073cb00-7475-11eb-95aa-ae02f0f35bc8.png)

**This also impacts testing moveit on the environment (when using `load_moveit:=true`)**, because the joint controllers timeout while waiting for a service because of the extra time, crashing and leaving the simulation unable to be controlled using rviz/moveit once it finally loads.

Commenting out the section here https://github.com/usnistgov/ARIAC/blob/master/nist_gear/config/sample-test.yaml#L116 allows the simulation to load much faster and allows to test moveit on the environment.

**Comment by zeidk** [comment]
A big update will be pushed tomorrow that should fix all the current issues.

**Comment by glpuga** [comment]
This is fixed in the latest release, so I'm closing this issue.

**Comment by glpuga** [comment]
Thanks!
