### ISSUE TITLE
scoring

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#61]
I found the section that describes scoring for parts on the tray, but it does not mention how the scoring works for assembled parts.

**Comment by denbar-robotics** [comment]
I realized that the assembly has the same paramters as the tray

**Comment by zeidk** [comment]
They have similar scoring metrics but I will update the page to make it clear.

**Comment by zeidk** [comment]
While we are making updates to the wiki here is a summary on assembly scoring:

"For the Assembly process, the completion score will be similarly calculated, with 2 points awarded for each part being successfully assembled, with a double all-parts bonus to make a maximum of 4 times the number of parts being inserted into the assembly (so for the ventilator briefcase design, it would be a maximum of 16 points for a fully completed ventilator) (4 x 4 = 16)."

**Comment by denbar-robotics** [comment]
Any points for getting a part into the briefcase, but not correctly oriented?

**Comment by zeidk** [comment]
> Any points for getting a part into the briefcase, but not correctly oriented?

@anthonydowns Any thoughts here?

We are also working on the assembly plugin to keep parts in place once positioned. Just letting you know since you are currently focusing on assembly.

**Comment by zeidk** [comment]
Documentation was updated a while ago regarding this question. Closing this one. Let me know if the documentation on scoring does not answer this question.
