### ISSUE TITLE
Error/Segmentattion fault spawning the ganty

### ISSUE THREAD

**Issue by GerardHarkemaAvans** [usnistgov/ARIAC#64]
When starting the sample_environment.launch gazebo crashes. After some searching i find out that spawning the gantry cause this crash. It is in the file "gantry.launch". Commenting out the following lines stops the crashes but the gantry is not loaded into Gazebo.

    
    <node name="gantry_spawner" pkg="gazebo_ros" type="spawn_model" respawn="false" output="screen"
          args="-urdf -model gantry -param robot_description
	  -J small_long_joint -1.45
    -J torso_rail_joint 0
	  -J torso_base_main_joint 0
    -J torso_main_torso_tray_joint 0
    -J gantry_arm_shoulder_pan_joint 0.00
    -J gantry_arm_shoulder_lift_joint -1.13
    -J gantry_arm_elbow_joint 1.88
    -J gantry_arm_wrist_1_joint -0.72
    -J gantry_arm_wrist_2_joint 1.55
    -J gantry_arm_wrist_3_joint 0.83"/>

**Comment by zeidk** [comment]
Hello, can you please try removing only `-J torso_main_torso_tray_joint 0` and see if it loads?

**Comment by GerardHarkemaAvans** [comment]
Sorry, tried your suggestion, loading still fails. Removed all joint all and it  still won´t load.

Hope this dump will help you.
... logging to /home/gerard/.ros/log/dbe7c5ce-7d33-11eb-87e8-b8aeedf4e998/roslaunch-gerard-ubuntu-4142.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://gerard-ubuntu:41485/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    ariac_sim (nist_gear/gear.py)

auto-starting new master
process[master]: started with pid [4152]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to dbe7c5ce-7d33-11eb-87e8-b8aeedf4e998
process[rosout-1]: started with pid [4163]
started core service [/rosout]
process[ariac_sim-2]: started with pid [4170]
writing file /tmp/ariac/gear.urdf.xacro
writing file /tmp/ariac/ariac.world
writing file /tmp/ariac/gear.launch
writing file /tmp/ariac/gantry.urdf.xacro
writing file /tmp/ariac/kitting.urdf.xacro
Running command: roslaunch /tmp/ariac/gear.launch world_path:=/tmp/ariac/ariac.world gear_urdf_xacro:=/tmp/ariac/gear.urdf.xacro gantry_urdf_xacro:=/tmp/ariac/gantry.urdf.xacro kitting_urdf_xacro:=/tmp/ariac/kitting.urdf.xacro
... logging to /home/gerard/.ros/log/dbe7c5ce-7d33-11eb-87e8-b8aeedf4e998/roslaunch-gerard-ubuntu-4173.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://gerard-ubuntu:33589/

SUMMARY
========

PARAMETERS
 * /ariac/gantry/gantry_arm_controller/action_monitor_rate: 10
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_elbow_joint/goal: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_elbow_joint/trajectory: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_shoulder_lift_joint/goal: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_shoulder_lift_joint/trajectory: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_shoulder_pan_joint/goal: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_shoulder_pan_joint/trajectory: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_wrist_1_joint/goal: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_wrist_1_joint/trajectory: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_wrist_2_joint/goal: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_wrist_2_joint/trajectory: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_wrist_3_joint/goal: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/gantry_arm_wrist_3_joint/trajectory: 0.1
 * /ariac/gantry/gantry_arm_controller/constraints/goal_time: 0.6
 * /ariac/gantry/gantry_arm_controller/constraints/stopped_velocity_tolerance: 0.05
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_elbow_joint/d: 150
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_elbow_joint/i: 1
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_elbow_joint/i_clamp: 25
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_elbow_joint/p: 50000
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_shoulder_lift_joint/d: 150
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_shoulder_lift_joint/i: 10
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_shoulder_lift_joint/i_clamp: 50
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_shoulder_lift_joint/p: 50000
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_shoulder_pan_joint/d: 150
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_shoulder_pan_joint/i: 0
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_shoulder_pan_joint/i_clamp: 1
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_shoulder_pan_joint/p: 10000
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_1_joint/d: 5
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_1_joint/i: 0
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_1_joint/i_clamp: 1
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_1_joint/p: 100
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_2_joint/d: 2
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_2_joint/i: 0
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_2_joint/i_clamp: 1
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_2_joint/p: 75
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_3_joint/d: 1
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_3_joint/i: 0
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_3_joint/i_clamp: 1
 * /ariac/gantry/gantry_arm_controller/gains/gantry_arm_wrist_3_joint/p: 25
 * /ariac/gantry/gantry_arm_controller/joints: ['gantry_arm_shou...
 * /ariac/gantry/gantry_arm_controller/state_publish_rate: 25
 * /ariac/gantry/gantry_arm_controller/stop_trajectory_duration: 0.5
 * /ariac/gantry/gantry_arm_controller/type: effort_controller...
 * /ariac/gantry/gantry_controller/action_monitor_rate: 10
 * /ariac/gantry/gantry_controller/constraints/goal_time: 0.6
 * /ariac/gantry/gantry_controller/constraints/small_long_joint/goal: 0.1
 * /ariac/gantry/gantry_controller/constraints/small_long_joint/trajectory: 0.1
 * /ariac/gantry/gantry_controller/constraints/stopped_velocity_tolerance: 0.05
 * /ariac/gantry/gantry_controller/constraints/torso_base_main_joint/goal: 0.1
 * /ariac/gantry/gantry_controller/constraints/torso_base_main_joint/trajectory: 0.1
 * /ariac/gantry/gantry_controller/constraints/torso_rail_joint/goal: 0.1
 * /ariac/gantry/gantry_controller/constraints/torso_rail_joint/trajectory: 0.1
 * /ariac/gantry/gantry_controller/gains/small_long_joint/d: 500
 * /ariac/gantry/gantry_controller/gains/small_long_joint/i: 0
 * /ariac/gantry/gantry_controller/gains/small_long_joint/i_clamp: 1
 * /ariac/gantry/gantry_controller/gains/small_long_joint/p: 100000
 * /ariac/gantry/gantry_controller/gains/torso_base_main_joint/d: 500
 * /ariac/gantry/gantry_controller/gains/torso_base_main_joint/i: 0
 * /ariac/gantry/gantry_controller/gains/torso_base_main_joint/i_clamp: 1
 * /ariac/gantry/gantry_controller/gains/torso_base_main_joint/p: 10000
 * /ariac/gantry/gantry_controller/gains/torso_rail_joint/d: 500
 * /ariac/gantry/gantry_controller/gains/torso_rail_joint/i: 0
 * /ariac/gantry/gantry_controller/gains/torso_rail_joint/i_clamp: 1
 * /ariac/gantry/gantry_controller/gains/torso_rail_joint/p: 100000
 * /ariac/gantry/gantry_controller/joints: ['small_long_join...
 * /ariac/gantry/gantry_controller/state_publish_rate: 25
 * /ariac/gantry/gantry_controller/stop_trajectory_duration: 0.5
 * /ariac/gantry/gantry_controller/type: effort_controller...
 * /ariac/gantry/joint_state_controller/publish_rate: 50
 * /ariac/gantry/joint_state_controller/type: joint_state_contr...
 * /ariac/gantry/robot_description: <?xml version="1....
 * /ariac/kitting/joint_state_controller/extra_joints: [{'position': 0.0...
 * /ariac/kitting/joint_state_controller/publish_rate: 50
 * /ariac/kitting/joint_state_controller/type: joint_state_contr...
 * /ariac/kitting/kitting_arm_controller/action_monitor_rate: 10
 * /ariac/kitting/kitting_arm_controller/constraints/elbow_joint/goal: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/elbow_joint/trajectory: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/goal_time: 0.6
 * /ariac/kitting/kitting_arm_controller/constraints/linear_arm_actuator_joint/goal: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/linear_arm_actuator_joint/trajectory: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/shoulder_lift_joint/trajectory: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/shoulder_pan_joint/trajectory: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/stopped_velocity_tolerance: 0.05
 * /ariac/kitting/kitting_arm_controller/constraints/wrist_1_joint/goal: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/wrist_1_joint/trajectory: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/wrist_2_joint/goal: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/wrist_2_joint/trajectory: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/wrist_3_joint/goal: 0.1
 * /ariac/kitting/kitting_arm_controller/constraints/wrist_3_joint/trajectory: 0.1
 * /ariac/kitting/kitting_arm_controller/gains/elbow_joint/d: 150
 * /ariac/kitting/kitting_arm_controller/gains/elbow_joint/i: 1
 * /ariac/kitting/kitting_arm_controller/gains/elbow_joint/i_clamp: 25
 * /ariac/kitting/kitting_arm_controller/gains/elbow_joint/p: 50000
 * /ariac/kitting/kitting_arm_controller/gains/linear_arm_actuator_joint/d: 500
 * /ariac/kitting/kitting_arm_controller/gains/linear_arm_actuator_joint/i: 0
 * /ariac/kitting/kitting_arm_controller/gains/linear_arm_actuator_joint/i_clamp: 1
 * /ariac/kitting/kitting_arm_controller/gains/linear_arm_actuator_joint/p: 10000
 * /ariac/kitting/kitting_arm_controller/gains/shoulder_lift_joint/d: 150
 * /ariac/kitting/kitting_arm_controller/gains/shoulder_lift_joint/i: 10
 * /ariac/kitting/kitting_arm_controller/gains/shoulder_lift_joint/i_clamp: 50
 * /ariac/kitting/kitting_arm_controller/gains/shoulder_lift_joint/p: 50000
 * /ariac/kitting/kitting_arm_controller/gains/shoulder_pan_joint/d: 150
 * /ariac/kitting/kitting_arm_controller/gains/shoulder_pan_joint/i: 0
 * /ariac/kitting/kitting_arm_controller/gains/shoulder_pan_joint/i_clamp: 1
 * /ariac/kitting/kitting_arm_controller/gains/shoulder_pan_joint/p: 10000
 * /ariac/kitting/kitting_arm_controller/gains/wrist_1_joint/d: 5
 * /ariac/kitting/kitting_arm_controller/gains/wrist_1_joint/i: 0
 * /ariac/kitting/kitting_arm_controller/gains/wrist_1_joint/i_clamp: 1
 * /ariac/kitting/kitting_arm_controller/gains/wrist_1_joint/p: 100
 * /ariac/kitting/kitting_arm_controller/gains/wrist_2_joint/d: 2
 * /ariac/kitting/kitting_arm_controller/gains/wrist_2_joint/i: 0
 * /ariac/kitting/kitting_arm_controller/gains/wrist_2_joint/i_clamp: 1
 * /ariac/kitting/kitting_arm_controller/gains/wrist_2_joint/p: 75
 * /ariac/kitting/kitting_arm_controller/gains/wrist_3_joint/d: 1
 * /ariac/kitting/kitting_arm_controller/gains/wrist_3_joint/i: 0
 * /ariac/kitting/kitting_arm_controller/gains/wrist_3_joint/i_clamp: 1
 * /ariac/kitting/kitting_arm_controller/gains/wrist_3_joint/p: 25
 * /ariac/kitting/kitting_arm_controller/joints: ['linear_arm_actu...
 * /ariac/kitting/kitting_arm_controller/state_publish_rate: 25
 * /ariac/kitting/kitting_arm_controller/stop_trajectory_duration: 0.5
 * /ariac/kitting/kitting_arm_controller/type: effort_controller...
 * /ariac/kitting/robot_description: <?xml version="1....
 * /gazebo/enable_ros_network: True
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /sensors_description: <?xml version="1....
 * /sensors_tf_publisher/publish_frequency: 50.0
 * /sensors_tf_publisher/tf_prefix: 
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    gazebo_unpauser (nist_gear/gazebo_unpauser.py)
    sensors_tf_publisher (robot_state_publisher/robot_state_publisher)
    spawn_gazebo_sensors (gazebo_ros/spawn_model)
    startup_ariac (nist_gear/startup.sh)
  /ariac/gantry/
    gantry_controller_spawner (controller_manager/spawner)
    gantry_spawner (gazebo_ros/spawn_model)
    joint_state_controller_spawner (controller_manager/spawner)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
  /ariac/kitting/
    fake_joint_calibration (rostopic/rostopic)
    joint_state_controller_spawner (controller_manager/spawner)
    kitting_controller_spawner (controller_manager/spawner)
    kitting_spawner (gazebo_ros/spawn_model)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)

ROS_MASTER_URI=http://localhost:11311

process[startup_ariac-1]: started with pid [4197]
Ensuring scoring log file exists
File already exists: /home/gerard/.ariac/log/performance.log
[startup_ariac-1] process has finished cleanly
log file: /home/gerard/.ros/log/dbe7c5ce-7d33-11eb-87e8-b8aeedf4e998/startup_ariac-1*.log
process[gazebo-2]: started with pid [4199]
process[gazebo_gui-3]: started with pid [4204]
process[sensors_tf_publisher-4]: started with pid [4209]
process[spawn_gazebo_sensors-5]: started with pid [4210]
process[ariac/gantry/joint_state_controller_spawner-6]: started with pid [4211]
process[ariac/gantry/robot_state_publisher-7]: started with pid [4216]
process[ariac/gantry/gantry_spawner-8]: started with pid [4220]
process[ariac/gantry/gantry_controller_spawner-9]: started with pid [4224]
process[ariac/kitting/joint_state_controller_spawner-10]: started with pid [4225]
process[ariac/kitting/robot_state_publisher-11]: started with pid [4227]
process[ariac/kitting/kitting_spawner-12]: started with pid [4230]
process[ariac/kitting/fake_joint_calibration-13]: started with pid [4235]
process[ariac/kitting/kitting_controller_spawner-14]: started with pid [4237]
process[gazebo_unpauser-15]: started with pid [4238]
No handlers could be found for logger "rosout"
[INFO] [1614894728.868217, 0.000000]: Controller Spawner: Waiting for service /ariac/gantry/controller_manager/load_controller
[INFO] [1614894728.874286, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1614894728.886578, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1614894728.935021, 0.000000]: Controller Spawner: Waiting for service /ariac/kitting/controller_manager/load_controller
[ INFO] [1614894729.235661317]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1614894729.237829252]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1614894729.350947, 0.000000]: Loading model XML from ros parameter sensors_description
[INFO] [1614894729.354773, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1614894729.458695056]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1614894729.461273713]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[INFO] [1614894729.499284, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1614894729.506613, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1614894729.677605, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1614894729.688429, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1614894732.518445, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1614894732.522665164]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
[INFO] [1614894732.680466, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1614894732.700204, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1614894733.704654571]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1614894733.704718483]: Starting Laser Plugin (ns = /)
[ INFO] [1614894733.706631343]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1614894733.729885518]: Range plugin missing <updateRate>, defaults to 0
[INFO] [1614894733.937904, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[INFO] [1614894733.939201, 0.000000]: Waiting for service /gazebo/set_model_configuration
[INFO] [1614894733.941532, 0.000000]: temporary hack to **fix** the -J joint position option (issue #93), sleeping for 1 second to avoid race condition.
[ INFO] [1614894733.948772326]: Physics dynamic reconfigure ready.
[ INFO] [1614894733.969709905]: Loading gazebo_ros_control plugin
[ INFO] [1614894733.969917547]: Starting gazebo_ros_control plugin in namespace: /ariac/kitting/
[ INFO] [1614894733.970645061]: gazebo_ros_control plugin is waiting for model URDF in parameter [/ariac/kitting/robot_description] on the ROS param server.
[ INFO] [1614894734.091278670]: Loaded gazebo_ros_control.
[INFO] [1614894734.295919, 0.000000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1614894734.298296, 0.000000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1614894734.300309, 0.000000]: Loading controller: joint_state_controller
[ WARN] [1614894734.310037108]: Joint state interface already contains specified extra joint 'vacuum_gripper_joint'.
[INFO] [1614894734.310501, 0.000000]: Controller Spawner: Loaded controllers: joint_state_controller
[INFO] [1614894734.332646, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[INFO] [1614894734.367848, 0.000000]: Controller Spawner: Waiting for service /ariac/kitting/controller_manager/switch_controller
[INFO] [1614894734.370316, 0.000000]: Controller Spawner: Waiting for service /ariac/kitting/controller_manager/unload_controller
[INFO] [1614894734.373070, 0.000000]: Loading controller: kitting_arm_controller
[spawn_gazebo_sensors-5] process has finished cleanly
log file: /home/gerard/.ros/log/dbe7c5ce-7d33-11eb-87e8-b8aeedf4e998/spawn_gazebo_sensors-5*.log
[ INFO] [1614894734.830603983]: Camera Plugin: Using the 'robotNamespace' param: '/ariac/gantry/'
[ INFO] [1614894734.834015236]: Camera Plugin (ns = /ariac/gantry/)  <tf_prefix_>, set to "/ariac/gantry"
[INFO] [1614894734.834670, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[INFO] [1614894734.943968, 0.000000]: Calling service /gazebo/set_model_configuration
[INFO] [1614894734.946877, 0.000000]: Set model configuration status: SetModelConfiguration: success
[ariac/gantry/gantry_spawner-8] process has finished cleanly
log file: /home/gerard/.ros/log/dbe7c5ce-7d33-11eb-87e8-b8aeedf4e998/ariac-gantry-gantry_spawner-8*.log
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 212, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 190, in main
    resp = load_controller(name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 532, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[INFO] [1614894735.143586, 0.000000]: Shutting down spawner. Stopping and unloading controllers...
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 212, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/melodic/lib/controller_manager/spawner", line 204, in main
    resp = switch_controller(loaded, [], 2, False, 0.0)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 532, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[INFO] [1614894735.144433, 0.000000]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1614894735.146152, 0.000000]: Stopping all controllers...
[INFO] [1614894735.146897, 0.000000]: Stopping all controllers...
[WARN] [1614894735.161375, 0.000000]: Controller Spawner error while taking down controllers: unable to connect to service: [Errno 104] Connection reset by peer
[WARN] [1614894735.162094, 0.000000]: Controller Spawner error while taking down controllers: unable to connect to service: [Errno 104] Connection reset by peer
Segmentation fault (core dumped)
================================================================================REQUIRED process [gazebo-2] has died!
process has died [pid 4199, exit code 139, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -u -e ode /tmp/ariac/ariac.world __name:=gazebo __log:=/home/gerard/.ros/log/dbe7c5ce-7d33-11eb-87e8-b8aeedf4e998/gazebo-2.log].
log file: /home/gerard/.ros/log/dbe7c5ce-7d33-11eb-87e8-b8aeedf4e998/gazebo-2*.log
Initiating shutdown!
================================================================================
[gazebo_unpauser-15] killing on exit
Traceback (most recent call last):
  File "/home/gerard/ariac2021_ws/src/nist_gear/script/gazebo_unpauser.py", line 33, in <module>
    time.sleep(3)
KeyboardInterrupt
[ariac/kitting/kitting_controller_spawner-14] killing on exit
[ariac/kitting/robot_state_publisher-11] killing on exit
[ariac/kitting/fake_joint_calibration-13] killing on exit
[ariac/kitting/kitting_spawner-12] killing on exit
[ariac/gantry/gantry_controller_spawner-9] killing on exit
[ariac/gantry/robot_state_publisher-7] killing on exit
[ariac/gantry/joint_state_controller_spawner-6] killing on exit
[sensors_tf_publisher-4] killing on exit
[ariac/kitting/joint_state_controller_spawner-10] killing on exit
[gazebo_gui-3] killing on exit
[gazebo-2] killing on exit
[WARN] [1614894735.478588, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[WARN] [1614894735.527391, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[gazebo_gui-3] escalating to SIGTERM
shutting down processing monitor...
... shutting down processing monitor complete
done
================================================================================REQUIRED process [ariac_sim-2] has died!
process has finished cleanly
log file: /home/gerard/.ros/log/dbe7c5ce-7d33-11eb-87e8-b8aeedf4e998/ariac_sim-2*.log
Initiating shutdown!
================================================================================
[ariac_sim-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by zeidk** [comment]
I managed to reproduce the error on another computer. We are working on a fix.

**Comment by dan9thsense** [comment]
I made that change (see #59) and it helped with the REST error, but I still got a seg fault

**Comment by zeidk** [comment]
Since your issue is similar to the one described in #59 I will comment in the other ticket and not here. Please refer to my comments in the other ticket.

**Comment by stevegray954** [comment]
@GerardHarkemaAvans Please try updating your Gazebo version, as I posted about here:
https://github.com/usnistgov/ARIAC/issues/59?_pjax=%23js-repo-pjax-container#issuecomment-791934930

**Comment by GerardHarkemaAvans** [comment]
Yes!!!
This works. Thanks a lot.
Kind regards,

Gerard
