### ISSUE TITLE
will one order be updated many times? 

### ISSUE THREAD

**Issue by dongqingwei** [usnistgov/ARIAC#67]
![image](https://user-images.githubusercontent.com/43602739/110324785-6deeb980-8051-11eb-8d32-f8f120ef4ea6.png)
hello, in a trial, will one order be updated many times?  if one order will be updated many times, the original order ID is "order_0", the first update order ID is "order_0_update", is the second order ID "order_0_update_update"  ?

**Comment by zeidk** [comment]
Hello, an order can be updated only once (order_0_update). You will never have a situation where the same order is updated twice. Thank you for the question, I will also clarify this in the wiki.

**Comment by dongqingwei** [comment]
Ok, thanks for your answer.
