### ISSUE TITLE
gantry self collision

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#74]
When trying to move the gantry, any move that is more than a nudge away from the initial location produces a collision with this message

`Found a contact between 'torso_tray' (type 'Robot link') and 'torso_main' (type 'Robot link'), which constitutes a collision. Contact information is not stored.`

**Comment by zeidk** [comment]
I updated the collision matrix and it's gone. I'm working to get an updated version pushed.

**Comment by zeidk** [comment]
Was this issue resolved. A new moveit package was pushed for the gantry a while ago.

**Comment by dan9thsense** [comment]
Yes, it is fixed.
