### ISSUE TITLE
Faulty Gripper

### ISSUE THREAD

**Issue by YunpengHe** [usnistgov/ARIAC#82]
When using 'sample_faulty_sensor.yam', 'assembly_sensor_blue' always falls on the lower left corner of the tray and the pose will change, so I want to confirm whether it will drop it like this when the final game. 

![drops](https://user-images.githubusercontent.com/71024833/111748053-00e9e800-88cb-11eb-8aab-c7c306a00016.png)

**Comment by zeidk** [comment]
Hello, the only thing that is guaranteed is that the part will fall in the tray and not on the floor. Where it falls in the tray can change between trials. We are trying to mimic a real situation with a faulty gripper.
