### ISSUE TITLE
I can’t install the regulator component in the briefcase, there will be a bug that jitters and then falls. 

### ISSUE THREAD

**Issue by fengyongchaoshen** [usnistgov/ARIAC#91]

**Comment by zeidk** [comment]
@Pavel-P Can you take a look at this asap?

**Comment by zeidk** [comment]
We are still working on this one. As such, the qualifiers will not ask you to do assembly with parts that are placed on the sides of the ventilator. Only parts placed on the flat surface of the ventilator will be used (battery and pump).

**Comment by fengyongchaoshen** [comment]
When will the preliminaries be held and have they been postponed?

**Comment by zeidk** [comment]
Just to let you know that assembly used during the qualifiers will only use the pump and the battery and not the 2 other parts.

**Comment by mqt0029** [comment]
Does this extends to kitting as well, or kitting still use all parts, just assembly will be using the pump and battery exclusively?

**Comment by barrygxwan** [comment]
> Just to let you know that assembly used during the qualifiers will only use the pump and the battery and not the 2 other parts.

hi，zeidk.
       is this issue is fixed?

**Comment by zeidk** [comment]
@Pavel-P Has the assembly plugin been fixed? If so, we will include the regulator and the sensor as part of the assembly.
