### ISSUE TITLE
Part always fall on the ground in “sample_faulty_gripper.yaml”

### ISSUE THREAD

**Issue by barrygxwan** [usnistgov/ARIAC#92]
Does the parts fall on the ground during competition？

**Comment by zeidk** [comment]
No, parts should always fall in the tray. It seems this is dependent of the part type based on what you are saying. I will be pushing a new update today that will take care of many current issues, including this one.

**Comment by barrygxwan** [comment]
ok, thank you

**Comment by zeidk** [comment]
Please switch to the branch merge_april_test and try it again. I changed the x value for the destination in the config file to make the part drop in the tray.
