### ISSUE TITLE
blackouts trigger at start

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#96]
Using this form:
sensor_blackout:
  product_count: 2 #sensor blackout triggered after second product is placed
  duration: 50

the blackout always triggers at the start, it does not wait. See here it is triggered at 5 seconds:

[ INFO] [1619063101.089851641, 5.004000000]: Triggering sensor blackout because 2 products detected.

**Comment by zeidk** [comment]
This is expected if a total of 2 products is in all the combined AGVs, which seems to be the case. If you show me the trial file used I can tell you if the behavior is correct or not.

**Comment by denbar-robotics** [comment]
OK, I thought it would happen after placing 2 products.  Thanks for the info.
