### ISSUE TITLE
qualifiers

### ISSUE THREAD

**Issue by denbar-robotics** [usnistgov/ARIAC#98]
Submissions for qualifiers are due May 3rd but the automated evaluation procedure instructions page is blank.  How do we submit?https://github.com/usnistgov/ARIAC/blob/ariac2021/wiki/tutorials/automated_evaluation.md

**Comment by zeidk** [comment]
Hi Dan, I will be pushing a new update tonight in the master branch and you will have the needed explanations.
I will talk to Craig tomorrow to push the qualifiers deadline to next Monday. We were having difficulties with the docker website to push the image and this delayed a few things.
